namespace DofusRetroAPI.Entities.Items.Resources;

public enum ResourceType
{
    Resource = 15,
    Cereal = 34,
    Flower = 35,
    Plant = 36,
    Wood = 38,
    Ore = 39,
    Alloy = 40,
    Fish = 41,
    Fruit = 46,
    Bone = 47,
    Powder = 48,
    PreciousStone = 50,
    Stone = 51,
    Flour = 52,
    Feather = 53,
    Hair = 54,
    Fabric = 55,
    Leather = 56,
    Wool = 57,
    Seed = 58,
    Skin = 59,
    Oil = 60,
    StuffedAnimal = 61,
    GuttedFish = 62,
    Meat = 63,
    PreservedMeat = 64,
    Tail = 65,
    Metaria = 66,
    Vegetable = 68,
    AlchemyEquipment = 71,
    SmithmagicRune = 78,
    Keys = 84,
    PetGhost = 90,
    Plank = 95,
    Bark = 96,
    Root = 98,
    Leg = 103,
    Wing = 104,
    Egg = 105,
    Ear = 106,
    Carapace = 107,
    Bud = 108,
    Eye = 109,
    Jelly = 110,
    Shell = 111,
//     AlchemyEquipment,
//     Alloy,
//     Bark,
//     Bone,
//     Bud,
//     Carapace,
//     Cereal = 34,
//     Ear,
//     Egg,
//     Eye,
//     Fabric,
//     Feather,
//     Fish,
//     Flour,
//     Flower = 35,
//     Fruit,
//     GuttedFish,
//     Hair,
//     Jelly,
//     Key,
//     Leather,
//     Leg,
//     Meat,
//     Metaria,
//     Oil,
//     Ore = 39,
//     PetGhost,
//     Plant = 36, 
//     Plank,
//     Powder,
//     PreciousStone,
//     PreservedMeat,
//     Resource = 15,
//     Root,
//     Seed,
//     Shell,
//     Skin,
//     SmithMagicPotion = 26,
//     SmithMagicRune,
//     Stone,
//     StuffedAnimal,
//     Tail,
//     Vegetable,
//     Wing,
//     Wood = 38,
//     Wool
  
}

