namespace ClassLibrary.Enums.Stats;

public enum StatType
{
    Teleport = 4,
    MoveBack = 5,
    MoveForward = 6,
    Divorce = 7,
    SwapPlayerPositions = 8,
    AvoidHitsByMovingBakc = 9,
    AllowEmoticon = 10,
    ChangePlayingTime = 13,
    CarryPlayer = 50,
    ThrowPlayer = 51,
    StealMp = 77,
    AddMp = 78,
    DamageReceivedMultipliedOrHealed = 79,
    HpRestored = 81,
    StealsHpFixed = 82,
    StealsAp = 84,
    DamageSelfWater = 85,
    DamageSelfEarth = 86,
    DamageSelfAir = 87,
    DamageSelfFire = 88,
    DamageSelfNeutral = 89,
    GiveOwnLife = 90,
    StealWater = 91,
    StealEarth = 92,
    StealAir = 93,
    StealFire = 94,
    StealNeutral = 95,
    DamageWater = 96,
    DamageEarth = 97,
    DamageAir = 98,
    DamageFire = 99,
    DamageNeutral = 100,
    LostApForTarget = 101,
    DamageReducedRangedPercentage = 105,
    ReflectSpell = 106,
    ReflectDamage = 107,
    HpRestored2 = 108,
    DamageToCaster = 109,
    XLife = 110,
    XAp = 111,
    XDamage = 112,
    DoubleDamageOrRestoreHp = 113,
    MultiplyDamage = 114,
    PlusCriticalHits = 115,
    RemoveRange = 116,
    AddRange = 117,
    AddStrength = 118,
    AddAgility = 119,
    AddAp = 120,
    AddDamage = 121,
    AddCriticalFailures = 122,
    AddChance = 123,
    AddWisdom = 124,
    AddVitality = 125,
    AddIntelligence = 126,
    MpLost = 127,
    PlusMp = 128,
    StealsKamas = 130,
    UsingApLosesHp = 131,
    Debuff = 132,
    LostApForCaster = 133,
    LostMpForCaster = 134,
    CasterRangeReduced = 135,
    CasterRangeIncreased = 136,
    CasterPhysicalDamageIncrease = 137,
    DamageIncreasePercentage = 138,
    RestoreEnergyPoints = 139,
    SkipATurn = 140,
    KillTarget = 141,
    AddPhysicalDamage = 142,
    HpRestored3 = 143,
    DamageUnboosted = 144,
    RemoveDamage = 145,
    ChangesTheWords = 146,
    ReviveAlly = 147,
    SomeoneFollowingYou = 148,
    ChangeAppearance = 149,
    MakeCharacterInvisible = 150,
    RemoveChance = 152,
    RemoveVitality = 153,
    RemoveAgility = 154,
    RemoveIntelligence = 155,
    RemoveWisdom = 156,
    RemoveStrength = 157,
    IncreaseLoadWeight = 158,
    DecreaseLoadWeight = 159,
    IncreaseChanceOfAvoidingApLoss = 160,
    IncreaseChanceOfAvoidingMpLoss = 161,
    DecreaseChanceOfAvoidingApLoss = 162,
    DecreaseChanceOfAvoidingMpLoss = 163,
    DamageReducedFixedPercentage = 164,
    IncreaseDamageByPercentage = 165,
    ApGivenBackRange = 166,
    DecreaseAp = 168,
    DecreaseMp = 169,
    DecreaseCriticalHits = 171,
    MagicResistanceDecreasedByRange = 172,
    PhysicalReductionDecreasedByRange = 173,
    AddInitiative = 174,
    RemoveInitiative = 175,
    AddProspecting = 176,
    RemoveProspecting = 177,
    AddBonusHealing = 178,
    RemoveBonusHealing = 179,
    CreateDouble = 180,
    Summons = 181,
    AddSummunonableCreatures = 182,
    MagicReductionOfRange = 183,
    PhysicalReductionOfRange = 184,
    SummonStaticCreature = 185,
    DecreaseDamageByRangePercentage = 186,
    SwitchAlignment = 188,
    GainKamasRange = 194,
    TransformInto = 197,
    PutItemOnTheGround = 201,
    RevealAllInvisibleItems = 202,
    ReviveTheTarget = 206,
    PercentageEarthResistance = 210,
    PercentageWaterResistance = 211,
    PercentageAIrResistance = 212,
    PercentageFireResistance = 213,
    PercentageNeutralResistance = 214,
    PercentageEarthWeakness = 215,
    PercentageWaterWeakness = 216,
    PercentageAirWeakness = 217,
    PercentageFireWeakness = 218,
    PercentageNeutralWeakness = 219,
    ReflectDamageRange = 220,
    WhatsInThere = 221,
    WhatsInThere2 = 222,
    AddTrapDamage = 225,
    AddTrapDamagePercentage = 226,
    GetAMount = 229,
    LostEnergy = 230,
    TransformInto2 = 239,
    AddPercentageEarthResistanceRange = 240,
    AddPercentageWaterResistanceRange = 241,
    AddPercentageAirResistanceRange = 242,
    AddPercentageFireResistanceRange = 243,
    AddPercentageNeutralResistanceRange = 244,
    RemovePercentageEarthResistanceRange = 245,
    RemovePercentageWaterResistanceRange = 246,
    RemovePercentageAirResistanceRange = 247,
    RemovePercentageFireResistanceRange = 248,
    RemovePercentageNeutralResistanceRange = 249,
    PercentageEarthResistanceAgainstFightersRange = 250,
    PercentageWaterResistanceAgainstFightersRange = 251,
    PercentageAirResistanceAgainstFightersRange = 252,
    PercentageFireResistanceAgainstFightersRange = 253,
    PercentageNeutralResistanceAgainstFightersRange = 254,
    PercentageEarthWeaknessAgainstFightersRange = 255,
    PercentageWaterWeaknessAgainstFightersRange = 256,
    PercentageAirWeaknessAgainstFightersRange = 257,
    PercentageFireWeaknessAgainstFightersRange = 258,
    PercentageNeutralWeaknessAgainstFightersRange = 259,
    
    
    
    
    
    
    
    
    
    
    
    
    
     
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // Main effects and equipment effects
    Vitality = 1,
    Wisdom = 2,
    Strength = 3,
    Intelligence = 4,
    Chance = 5,
    Agility = 6,
    ActionPoint = 7,
    MovementPoint = 8,
    Range = 9,
    SummonLimit = 10,
    CriticalHit = 11,
    BonusHeal = 12,
    Prospecting = 13,
    Pods = 14,
    Initiative = 15,
    DamageReflection = 16,
    TrapDamage = 17,
    TrapPower = 18,
    FixedDamage = 19,
    PercentageDamage = 20,
    NeutralFixedResistance = 21,
    EarthFixedResistance = 22,
    FireFixedResistance = 23,
    WaterFixedResistance = 24,
    AirFixedResistance = 25,
    NeutralPercentageResistance = 26,
    EarthPercentageResistance = 27,
    FirePercentageResistance = 28,
    WaterPercentageResistance = 29,
    AirPercentageResistance = 30,
    
    // Weapon Effects
    HuntingWeapon = 31,
    NeutralDamage = 32,
    EarthDamage = 33,
    FireDamage = 34,
    WaterDamage = 35,
    AirDamage = 36,
    NeutralLifeSteal = 37,
    EarthLifeSteal = 38,
    FireLifeSteal = 39,
    WaterLifeSteal = 40,
    AirLifeSteal = 41,
    Heal = 42,
    MinusActionPoint = 43,
    
    // Other effects
    EnhancesPetCapacity = 44,
    
    
    
}