namespace DofusRetroAPI.Entities.Items.Consumables;

public enum ConsumableType
{
    Bread,
    EdibleFish,
    EdibleMeat,
    Candy,
    Beer,
    Drink,
    Potion,
    SkillLossPotion,
    UnlearningPotionForProfession,
    ForgetfulnessPotion,
    ForgetfulnessPotionForCollectors,
    PetPotion,
    Dyeing,
    GiftItem,
    Document,
    Skill,
    ExperienceScroll,
    CharacteristicScroll,
    SpellScroll,
    MountCertificate,
    BowKennelCertificate,
    SeekerScroller,
    SpiritGem,
    BagOfResources,
    PetEgg,
    FairyWork,
    MagicStone,
    Gift,
    BreedingItem,
    UsableItem,
    QuestItem,
    Prism,
    FragmentOfShushuSoul
}