namespace ClassLibrary.Enums.Jobs;

public enum Jobs
{
    Lumberjack = 2,
    SwordSmith = 11,
    BowCarver = 13,
    HammerSmith = 14,
    ShoeMaker = 15,
    Jeweller = 16,
    DaggerSmith = 17,
    StaffCarver = 18,
    WandCarver = 19,
    ShovelSmith = 20,
    Miner = 24,
    Baker = 25,
    Alchemist = 26,
    Tailor = 27,
    Farmer = 28,
    AxeSmith = 31,
    Fisherman = 36,
    Hunter = 41,
    DaggerSmithmagus = 43,
    SwordSmithmagus = 44,
    HammerSmithmagus = 45,
    ShovelSmithmagus = 46,
    AxeSmithmagus = 47,
    BowSmithmagus = 48,
    WandSmithmagus = 49,
    StaffSmithmagus = 50,
    Butcher = 56,
    Fishmonger = 58,
    ShieldSmith = 60,
    Shoemagus,
    Jewelmagus,
    Costumagus,
    Handyman
}