namespace DofusRetroAPI.Entities.Effects;

public enum EffectType
{
    // All Items Effects
    Vitality,
    Wisdom,
    Strength,
    Intelligence,
    Chance,
    Agility,
    ActionPoint,
    MovementPoint,
    Range,
    SummonLimit,
    CriticalHit,
    BonusHeal,
    Prospecting,
    Pods,
    Initiative,
    DamageReflection,
    TrapDamage,
    TrapPower,
    FixedDamage,
    PercentageDamage,
    NeutralFixedResistance,
    EarthFixedResistance,
    FireFixedResistance,
    WaterFixedResistance,
    AirFixedResistance,
    NeutralPercentageResistance,
    EarthPercentageResistance,
    FirePercentageResistance,
    WaterPercentageResistance,
    AirPercentageResistance,
    
    // Weapon Effects
    NeutralDamage,
    EarthDamage,
    FireDamage,
    WaterDamage,
    AirDamage,
    NeutralLifeSteal,
    EarthLifeSteal,
    FireLifeSteal,
    WaterLifeSteal,
    AirLifeSteal,
    Heal,
    MinusActionPoint
}