namespace DofusRetroAPI.Entities.Items.Consumables;

public enum ConsumableType
{
    Bread = 33,
    EdibleFish,
    EdibleMeat,
    Candy,
    Beer = 37,
    Drink,
    Potion = 12,
    SkillLossPotion,
    UnlearningPotionForProfession,
    ForgetfulnessPotion,
    ForgetfulnessPotionForCollectors,
    PetPotion,
    Dye,
    Document = 25,
    Skill,
    ExperienceScroll = 13,
    CharacteristicScroll,
    SpellScroll,
    MountCertificate,
    BowKennelCertificate,
    SeekerScroll,
    SpiritGem,
    BagOfResources,
    PetEgg,
    FairyWork,
    MagicStone,
    GiftItem = 14,
    BreedingItem,
    UsableItem,
    QuestItem = 24,
    Prism,
    FragmentOfShushuSoul,
    MutationItem = 27,
    BoostFood = 28,
    Blessing = 29,
    Curse = 30,
    RolePlayBuff = 31,
    FollowingCharacter = 32,
}