using DofusRetroAPI.Entities.Items.Consumables;
using DofusRetroAPI.Entities.Items.Equipments;
using DofusRetroAPI.Entities.Items.Resources;
using DofusRetroAPI.Entities.Monsters.Breeds;
using DofusRetroAPI.Entities.Monsters.Ecosystems;
using DofusRetroClassLibrary.Enums.Localization;

namespace DofusRetroAPI.Localization;

public static class Localization
{
    static Localization()
    {
        if (EquipmentTypeNames == null || EquipmentTypeNames.Count == 0)
            EquipmentTypeNames = new ()
            {
                // FR Localization
                {(EquipmentType.Hat, Language.FR), "Chapeau"},
                {(EquipmentType.Cloak, Language.FR), "Cape"},
                {(EquipmentType.Backpack, Language.FR), "Sac à dos"},
                {(EquipmentType.Amulet, Language.FR), "Amulette"},
                {(EquipmentType.Belt, Language.FR), "Ceinture"},
                {(EquipmentType.Boots, Language.FR), "Bottes"},
                {(EquipmentType.Dofus, Language.FR), "Dofus"},
                {(EquipmentType.Pet, Language.FR), "Familier"},
                {(EquipmentType.Dragoturkey, Language.FR), "Dragodinde"},
                {(EquipmentType.SoulStone, Language.FR), "Pierre d'âme"},
                {(EquipmentType.CapturingNet, Language.FR), "Filet de capture"},
                {(EquipmentType.Staff, Language.FR), "Bâton"},
                {(EquipmentType.Bow, Language.FR), "Arc"},
                {(EquipmentType.Wand, Language.FR), "Baguette"},
                {(EquipmentType.Sword, Language.FR), "Épée"},
                {(EquipmentType.Hammer, Language.FR), "Marteau"},
                {(EquipmentType.Shovel, Language.FR), "Pelle"},
                {(EquipmentType.Daggers, Language.FR), "Dagues"},
                {(EquipmentType.Axe, Language.FR), "Hache"},
                {(EquipmentType.Tool, Language.FR), "Outil"},
                {(EquipmentType.Pickaxe, Language.FR), "Pioche"},
                {(EquipmentType.Scythe, Language.FR), "Faux"},
                {(EquipmentType.Crossbow, Language.FR), "Arbalète"},
                {(EquipmentType.MagicWeapon, Language.FR), "Arme magique"},
                {(EquipmentType.Ring, Language.FR), "Anneau"},
                {(EquipmentType.Shield, Language.FR), "Bouclier"},
        
                // English Localization
                {(EquipmentType.Hat, Language.EN), "Hat"},
                {(EquipmentType.Cloak, Language.EN), "Cloak"},
                {(EquipmentType.Backpack, Language.EN), "Backpack"},
                {(EquipmentType.Amulet, Language.EN), "Amulet"},
                {(EquipmentType.Belt, Language.EN), "Belt"},
                {(EquipmentType.Boots, Language.EN), "Boots"},
                {(EquipmentType.Dofus, Language.EN), "Dofus"},
                {(EquipmentType.Pet, Language.EN), "Pet"},
                {(EquipmentType.Dragoturkey, Language.EN), "Dragoturkey"},
                {(EquipmentType.SoulStone, Language.EN), "Soul stone"},
                {(EquipmentType.CapturingNet, Language.EN), "Capturing net"},
                {(EquipmentType.Staff, Language.EN), "Staff"},
                {(EquipmentType.Bow, Language.EN), "Bow"},
                {(EquipmentType.Wand, Language.EN), "Wand"},
                {(EquipmentType.Sword, Language.EN), "Sword"},
                {(EquipmentType.Hammer, Language.EN), "Hammer"},
                {(EquipmentType.Shovel, Language.EN), "Shovel"},
                {(EquipmentType.Daggers, Language.EN), "Daggers"},
                {(EquipmentType.Axe, Language.EN), "Axe"},
                {(EquipmentType.Tool, Language.EN), "Tool"},
                {(EquipmentType.Pickaxe, Language.EN), "Pickaxe"},
                {(EquipmentType.Scythe, Language.EN), "Scythe"},
                {(EquipmentType.Crossbow, Language.EN), "Crossbow"},
                {(EquipmentType.MagicWeapon, Language.EN), "MagicWeapon"},
                {(EquipmentType.Ring, Language.EN), "Ring"},
                {(EquipmentType.Shield, Language.EN), "Shield"},
        
                // Spanish Localization
                {(EquipmentType.Hat, Language.ES), "Sombrero"},
                {(EquipmentType.Cloak, Language.ES), "Capa"},
                {(EquipmentType.Backpack, Language.ES), "Mochila"},
                {(EquipmentType.Amulet, Language.ES), "Amulette"},
                {(EquipmentType.Belt, Language.ES), "Cinturón"},
                {(EquipmentType.Boots, Language.ES), "Botas"},
                {(EquipmentType.Dofus, Language.ES), "Dofus"},
                {(EquipmentType.Pet, Language.ES), "Mascota"},
                {(EquipmentType.Dragoturkey, Language.ES), "Dragopavo"},
                {(EquipmentType.SoulStone, Language.ES), "Piedra de alma"},
                {(EquipmentType.CapturingNet, Language.ES), "Red de captura"},
                {(EquipmentType.Staff, Language.ES), "Bastón"},
                {(EquipmentType.Bow, Language.ES), "Arco"},
                {(EquipmentType.Wand, Language.ES), "Varita"},
                {(EquipmentType.Sword, Language.ES), "Espada"},
                {(EquipmentType.Hammer, Language.ES), "Martillo"},
                {(EquipmentType.Shovel, Language.ES), "Pala"},
                {(EquipmentType.Daggers, Language.ES), "Daga"},
                {(EquipmentType.Axe, Language.ES), "Hacha"},
                {(EquipmentType.Tool, Language.ES), "Herramienta"},
                {(EquipmentType.Pickaxe, Language.ES), "Pico"},
                {(EquipmentType.Scythe, Language.ES), "Guadaña"},
                {(EquipmentType.Crossbow, Language.ES), "Ballesta"},
                {(EquipmentType.MagicWeapon, Language.ES), "Varita"},
                {(EquipmentType.Ring, Language.ES), "Anillo"},
                {(EquipmentType.Shield, Language.ES), "Escudo"}
        };
        
        if (ConsumableTypeNames == null || ConsumableTypeNames.Count == 0)
            ConsumableTypeNames = new ()
            {
                // FR names
                {(ConsumableType.Bread, Language.FR), "Pain"},
                {(ConsumableType.EdibleFish, Language.FR), "Poisson comestible"},
                {(ConsumableType.EdibleMeat, Language.FR), "Viande comestible"},
                {(ConsumableType.Candy, Language.FR), "Friandise"},
                {(ConsumableType.Beer, Language.FR), "Bière"},
                {(ConsumableType.Drink, Language.FR), "Boisson"},
                {(ConsumableType.Potion, Language.FR), "Potion"},
                {(ConsumableType.SkillLossPotion, Language.FR), "BasePotion d'oubli de maîtrise"},
                {(ConsumableType.UnlearningPotionForProfession, Language.FR), "BasePotion d'oubli de métier"},
                {(ConsumableType.ForgetfulnessPotion, Language.FR), "BasePotion d'oubli de sort"},
                {(ConsumableType.ForgetfulnessPotionForCollectors, Language.FR), "BasePotion d'oubli de percepteur"},
                {(ConsumableType.PetPotion, Language.FR), "BasePotion de familier"},
                {(ConsumableType.Dye, Language.FR), "Teinture"},
                {(ConsumableType.Document, Language.FR), "BaseDocument"},
                {(ConsumableType.Skill, Language.FR), "Maîtrise"},
                {(ConsumableType.ExperienceScroll, Language.FR), "Parchemin d'expérience"},
                {(ConsumableType.CharacteristicScroll, Language.FR), "Parchemin de caractéristique"},
                {(ConsumableType.SpellScroll, Language.FR), "Parchemin de sort"},
                {(ConsumableType.MountCertificate, Language.FR), "Certificat de monture"},
                {(ConsumableType.BowKennelCertificate, Language.FR), "Certificat de mise en chenil"},
                {(ConsumableType.SeekerScroll, Language.FR), "Parchemin de recherche"},
                {(ConsumableType.SpiritGem, Language.FR), "Gemme spirituelle"},
                {(ConsumableType.BagOfResources, Language.FR), "Sac de ressources"},
                {(ConsumableType.PetEgg, Language.FR), "Oeuf de familier"},
                {(ConsumableType.FairyWork, Language.FR), "Fée d'artifice"},
                {(ConsumableType.MagicStone, Language.FR), "Pierre magique"},
                {(ConsumableType.GiftItem, Language.FR), "Cadeau"},
                {(ConsumableType.BreedingItem, Language.FR), "Objet d'élevage"},
                {(ConsumableType.UsableItem, Language.FR), "Objet utilisable"},
                {(ConsumableType.QuestItem, Language.FR), "Objet de quête"},
                {(ConsumableType.Prism, Language.FR), "Prisme"},
                {(ConsumableType.FragmentOfShushuSoul, Language.FR), "Fragment d'âme de Shushu"},
                
                // English names
                {(ConsumableType.Bread, Language.EN), "Bread"},
                {(ConsumableType.EdibleFish, Language.EN), "Edible fish"},
                {(ConsumableType.EdibleMeat, Language.EN), "Edible meat"},
                {(ConsumableType.Candy, Language.EN), "Candy"},
                {(ConsumableType.Beer, Language.EN), "Beer"},
                {(ConsumableType.Drink, Language.EN), "Drink"},
                {(ConsumableType.Potion, Language.EN), "BasePotion"},
                {(ConsumableType.SkillLossPotion, Language.EN), "Skill loss potion"},
                {(ConsumableType.UnlearningPotionForProfession, Language.EN), "Unlearning potion for profession"},
                {(ConsumableType.ForgetfulnessPotion, Language.EN), "Forgetfulness potion"},
                {(ConsumableType.ForgetfulnessPotionForCollectors, Language.EN), "Forgetfulness potion for collectors"},
                {(ConsumableType.PetPotion, Language.EN), "Pet potion"},
                {(ConsumableType.Dye, Language.EN), "Dyeing"},
                {(ConsumableType.Document, Language.EN), "BaseDocument"},
                {(ConsumableType.Skill, Language.EN), "Skill"},
                {(ConsumableType.ExperienceScroll, Language.EN), "Experience scroll"},
                {(ConsumableType.CharacteristicScroll, Language.EN), "Characteristic scroll"},
                {(ConsumableType.SpellScroll, Language.EN), "Spell scroll"},
                {(ConsumableType.MountCertificate, Language.EN), "Mount certificate"},
                {(ConsumableType.BowKennelCertificate, Language.EN), "Bow kennel certificate"},
                {(ConsumableType.SeekerScroll, Language.EN), "Seeker scroller"},
                {(ConsumableType.SpiritGem, Language.EN), "Spirit gem"},
                {(ConsumableType.BagOfResources, Language.EN), "Bag of resources"},
                {(ConsumableType.PetEgg, Language.EN), "Pet egg"},
                {(ConsumableType.FairyWork, Language.EN), "Fairywork"},
                {(ConsumableType.MagicStone, Language.EN), "Magic stone"},
                {(ConsumableType.GiftItem, Language.EN), "Gift Item"},
                {(ConsumableType.BreedingItem, Language.EN), "Breeding Item"},
                {(ConsumableType.UsableItem, Language.EN), "Usable item"},
                {(ConsumableType.QuestItem, Language.EN), "Quest item"},
                {(ConsumableType.Prism, Language.EN), "Prism"},
                {(ConsumableType.FragmentOfShushuSoul, Language.EN), "Fragment of Shushu soul"},
                
                // Spanish names
                {(ConsumableType.Bread, Language.ES), "Pan"},
                {(ConsumableType.EdibleFish, Language.ES), "Pescado comestible"},
                {(ConsumableType.EdibleMeat, Language.ES), "Carne comestible"},
                {(ConsumableType.Candy, Language.ES), "Golosina"},
                {(ConsumableType.Beer, Language.ES), "Cerveza"},
                {(ConsumableType.Drink, Language.ES), "Bebida"},
                {(ConsumableType.Potion, Language.ES), "Pócima"},
                {(ConsumableType.SkillLossPotion, Language.ES), "Pócima de olvido de dominio"},
                {(ConsumableType.UnlearningPotionForProfession, Language.ES), "Poción de olvido de oficio"},
                {(ConsumableType.ForgetfulnessPotion, Language.ES), "Poción de olvido de hechizo"},
                {(ConsumableType.ForgetfulnessPotionForCollectors, Language.ES), "Poción de olvido de recaudador"},
                {(ConsumableType.PetPotion, Language.ES), "Poción de mascota"},
                {(ConsumableType.Dye, Language.ES), "Tinte"},
                {(ConsumableType.Document, Language.ES), "Documento"},
                {(ConsumableType.Skill, Language.ES), "Dominio"},
                {(ConsumableType.ExperienceScroll, Language.ES), "Pergamino de experiencia"},
                {(ConsumableType.CharacteristicScroll, Language.ES), "Pergamino de característica"},
                {(ConsumableType.SpellScroll, Language.ES), "Pergamino de hechizo"},
                {(ConsumableType.MountCertificate, Language.ES), "Certificado de montura"},
                {(ConsumableType.BowKennelCertificate, Language.ES), "Certificado de admisión en la petrera"},
                {(ConsumableType.SeekerScroll, Language.ES), "Pergamino de búsqueda"},
                {(ConsumableType.SpiritGem, Language.ES), "Gema espiritual"},
                {(ConsumableType.BagOfResources, Language.ES), "Sacos de recursos"},
                {(ConsumableType.PetEgg, Language.ES), "Huevo de mascota"},
                {(ConsumableType.FairyWork, Language.ES), "Hada artificial"},
                {(ConsumableType.MagicStone, Language.ES), "Piedra mágica"},
                {(ConsumableType.GiftItem, Language.ES), "Regalo"},
                {(ConsumableType.BreedingItem, Language.ES), "Objeto de cría"},
                {(ConsumableType.UsableItem, Language.ES), "Objeto utilizable"},
                {(ConsumableType.QuestItem, Language.ES), "Objeto de misión"},
                {(ConsumableType.Prism, Language.ES), "Prisma"},
                {(ConsumableType.FragmentOfShushuSoul, Language.ES), "Fragmento de alma de Fab'huritu"}
            };
        
        if (ResourceTypeNames == null || ResourceTypeNames.Count == 0)
            ResourceTypeNames = new ()
            {
                // FR names
                {(ResourceType.AlchemyEquipment, Language.FR), "Matériel  d'alchimie"},
                {(ResourceType.Alloy, Language.FR), "Alliage"},
                {(ResourceType.Bark, Language.FR), "Écorce"},
                {(ResourceType.Bone, Language.FR), "Os"},
                {(ResourceType.Bud, Language.FR), "Bourgeon"},
                {(ResourceType.Carapace, Language.FR), "Carapace"},
                {(ResourceType.Cereal, Language.FR), "Céréale"},
                {(ResourceType.Ear, Language.FR), "Oreille"},
                {(ResourceType.Egg, Language.FR), "Oeuf"},
                {(ResourceType.Eye, Language.FR), "Oeil"},
                {(ResourceType.Fabric, Language.FR), "Étoffe"},
                {(ResourceType.Feather, Language.FR), "Plume"},
                {(ResourceType.Fish, Language.FR), "Poisson"},
                {(ResourceType.Flour, Language.FR), "Farine"},
                {(ResourceType.Flower, Language.FR), "Fleur"},
                {(ResourceType.Fruit, Language.FR), "Fruit"},
                {(ResourceType.GuttedFish, Language.FR), "Poisson vidé"},
                {(ResourceType.Hair, Language.FR), "Poil"},
                {(ResourceType.Jelly, Language.FR), "Gelée"},
                {(ResourceType.Key, Language.FR), "Clef"},
                {(ResourceType.Leather, Language.FR), "Peau"},
                {(ResourceType.Leg, Language.FR), "Patte"},
                {(ResourceType.Meat, Language.FR), "Viande"},
                {(ResourceType.Metaria, Language.FR), "Metaria"},
                {(ResourceType.Oil, Language.FR), "Huile"},
                {(ResourceType.Ore, Language.FR), "Minerai"},
                {(ResourceType.PetGhost, Language.FR), "Fantôme de familier"},
                {(ResourceType.Plank, Language.FR), "Planche"},
                {(ResourceType.Powder, Language.FR), "Poudre"},
                {(ResourceType.PreciousStone, Language.FR), "Pierre précieuse"},
                {(ResourceType.PreservedMeat, Language.FR), "Viande conservée"},
                {(ResourceType.Resource, Language.FR), "Ressource"},
                {(ResourceType.Root, Language.FR), "Racine"},
                {(ResourceType.Seed, Language.FR), "Graine"},
                {(ResourceType.Shell, Language.FR), "Coquille"},
                {(ResourceType.Skin, Language.FR), "Peau"},
                {(ResourceType.SmithMagicPotion, Language.FR), "BasePotion de forgemagie"},
                {(ResourceType.SmithMagicRune, Language.FR), "Run de forgemagie"},
                {(ResourceType.Stone, Language.FR), "Pierre brute"},
                {(ResourceType.StuffedAnimal, Language.FR), "Peluche"},
                {(ResourceType.Tail, Language.FR), "Queue"},
                {(ResourceType.Vegetable, Language.FR), "Légume"},
                {(ResourceType.Wing, Language.FR), "Aile"},
                {(ResourceType.Wood, Language.FR), "Bois"},
                {(ResourceType.Wool, Language.FR), "Laine"},
                
                // English names
                {(ResourceType.AlchemyEquipment, Language.EN), "Alchemy equipment"},
                {(ResourceType.Alloy, Language.EN), "Alloy"},
                {(ResourceType.Bark, Language.EN), "Bark"},
                {(ResourceType.Bone, Language.EN), "Bone"},
                {(ResourceType.Bud, Language.EN), "Bud"},
                {(ResourceType.Carapace, Language.EN), "Carapace"},
                {(ResourceType.Cereal, Language.EN), "Cereal"},
                {(ResourceType.Ear, Language.EN), "Ear"},
                {(ResourceType.Egg, Language.EN), "Egg"},
                {(ResourceType.Eye, Language.EN), "Eye"},
                {(ResourceType.Fabric, Language.EN), "Fabric"},
                {(ResourceType.Feather, Language.EN), "Feather"},
                {(ResourceType.Fish, Language.EN), "Fish"},
                {(ResourceType.Flour, Language.EN), "Flour"},
                {(ResourceType.Flower, Language.EN), "Flower"},
                {(ResourceType.Fruit, Language.EN), "Fruit"},
                {(ResourceType.GuttedFish, Language.EN), "Gutted fish"},
                {(ResourceType.Hair, Language.EN), "Hair"},
                {(ResourceType.Jelly, Language.EN), "Jelly"},
                {(ResourceType.Key, Language.EN), "Key"},
                {(ResourceType.Leather, Language.EN), "Leather"},
                {(ResourceType.Leg, Language.EN), "Leg"},
                {(ResourceType.Meat, Language.EN), "Meat"},
                {(ResourceType.Metaria, Language.EN), "Metaria"},
                {(ResourceType.Oil, Language.EN), "Oil"},
                {(ResourceType.Ore, Language.EN), "Ore"},
                {(ResourceType.PetGhost, Language.EN), "Pet ghost"},
                {(ResourceType.Plank, Language.EN), "Plank"},
                {(ResourceType.Powder, Language.EN), "Powder"},
                {(ResourceType.PreciousStone, Language.EN), "Precious stone"},
                {(ResourceType.PreservedMeat, Language.EN), "Preserved meat"},
                {(ResourceType.Resource, Language.EN), "Resource"},
                {(ResourceType.Root, Language.EN), "Root"},
                {(ResourceType.Seed, Language.EN), "Seed"},
                {(ResourceType.Shell, Language.EN), "Shell"},
                {(ResourceType.Skin, Language.EN), "Skin"},
                {(ResourceType.SmithMagicPotion, Language.EN), "Smithmagic potion"},
                {(ResourceType.SmithMagicRune, Language.EN), "Smithmagic rune"},
                {(ResourceType.Stone, Language.EN), "Stone"},
                {(ResourceType.StuffedAnimal, Language.EN), "Stuffed animal"},
                {(ResourceType.Tail, Language.EN), "Tail"},
                {(ResourceType.Vegetable, Language.EN), "Vegetable"},
                {(ResourceType.Wing, Language.EN), "Wing"},
                {(ResourceType.Wood, Language.EN), "Wood"},
                {(ResourceType.Wool, Language.EN), "Wool"},
        
                // Spanish names
                {(ResourceType.AlchemyEquipment, Language.ES), "Material de alquimia"},
                {(ResourceType.Alloy, Language.ES), "Aleacion"},
                {(ResourceType.Bark, Language.ES), "Corteza"},
                {(ResourceType.Bone, Language.ES), "Hueso"},
                {(ResourceType.Bud, Language.ES), "Brote"},
                {(ResourceType.Carapace, Language.ES), "Carapazon"},
                {(ResourceType.Cereal, Language.ES), "Cereal"},
                {(ResourceType.Ear, Language.ES), "Oreja"},
                {(ResourceType.Egg, Language.ES), "Huevo"},
                {(ResourceType.Eye, Language.ES), "Ojo"},
                {(ResourceType.Fabric, Language.ES), "Tejido"},
                {(ResourceType.Feather, Language.ES), "Pluma"},
                {(ResourceType.Fish, Language.ES), "Pez"},
                {(ResourceType.Flour, Language.ES), "Harina"},
                {(ResourceType.Flower, Language.ES), "Flor"},
                {(ResourceType.Fruit, Language.ES), "Fruta"},
                {(ResourceType.GuttedFish, Language.ES), "Pescado vaciado"},
                {(ResourceType.Hair, Language.ES), "Pelo"},
                {(ResourceType.Jelly, Language.ES), "Gelatina"},
                {(ResourceType.Key, Language.ES), "Llave"},
                {(ResourceType.Leather, Language.ES), "Cuero"},
                {(ResourceType.Leg, Language.ES), "Pata"},
                {(ResourceType.Meat, Language.ES), "Carne"},
                {(ResourceType.Metaria, Language.ES), "Metaria"},
                {(ResourceType.Oil, Language.ES), "Aceite"},
                {(ResourceType.Ore, Language.ES), "Mineral"},
                {(ResourceType.PetGhost, Language.ES), "Fantasma de mascota"},
                {(ResourceType.Plank, Language.ES), "Tabla"},
                {(ResourceType.Powder, Language.ES), "Polvo"},
                {(ResourceType.PreciousStone, Language.ES), "Piedra preciosa"},
                {(ResourceType.PreservedMeat, Language.ES), "Carne conservada"},
                {(ResourceType.Resource, Language.ES), "Recurso"},
                {(ResourceType.Root, Language.ES), "Raíz"},
                {(ResourceType.Seed, Language.ES), "Semilla"},
                {(ResourceType.Shell, Language.ES), "Cascara"},
                {(ResourceType.Skin, Language.ES), "Piel"},
                {(ResourceType.SmithMagicPotion, Language.ES), "Pócima de forjamagia"},
                {(ResourceType.SmithMagicRune, Language.ES), "Runa de forjamagia"},
                {(ResourceType.Stone, Language.ES), "Piedra bruta"},
                {(ResourceType.StuffedAnimal, Language.ES), "Peluche"},
                {(ResourceType.Tail, Language.ES), "Cola"},
                {(ResourceType.Vegetable, Language.ES), "Legumbre"},
                {(ResourceType.Wing, Language.ES), "Ala"},
                {(ResourceType.Wood, Language.ES), "Madera"},
                {(ResourceType.Wool, Language.ES), "Lana"}
            };
        
        if (EcosystemNames == null || EcosystemNames.Count == 0)
            EcosystemNames = new ()
            {
                // FR names
                {(Ecosystem.VariousCreatures, Language.FR), "Créatures diverses"},
                {(Ecosystem.SwampCreatures, Language.FR), "Créatures des marécages"},
                {(Ecosystem.ForestCreatures, Language.FR), "Créatures de la forêt"},
                {(Ecosystem.PlainCreatures, Language.FR), "Créatures des plaines"},
                {(Ecosystem.FieldCreatures, Language.FR), "Créatures des champs"},
                {(Ecosystem.MoorCreatures, Language.FR), "Créatures des landes"},
                {(Ecosystem.MoonIslandCreatures, Language.FR), "Créatures de l'île de Moon"},
                {(Ecosystem.WabbitIslandCreatures, Language.FR), "Créatures de l'île des Wabbits"},
                {(Ecosystem.PandalaCreatures, Language.FR), "Créatures de Pandala"},
                {(Ecosystem.HumanoidCreatures, Language.FR), "Créatures humanoïdes"},
                {(Ecosystem.DarkCreatures, Language.FR), "Créatures de la nuit"},
                {(Ecosystem.ResourcesProtectors, Language.FR), "Protecteurs des ressources"},
                {(Ecosystem.CityCreatures, Language.FR), "Créatures des villes"},
                {(Ecosystem.BreederVillageCreatures, Language.FR), "Créatures du village des éleveurs"},
                {(Ecosystem.BeachCreatures, Language.FR), "Créatures des plages"},
                {(Ecosystem.MinotororIslandCreatures, Language.FR), "Créatures de l'île du Minotoror"},
                {(Ecosystem.MountainCreatures, Language.FR), "Créatures de la montagne"},
                {(Ecosystem.BeginnerAreaCreatures, Language.FR), "Créatures de la zone des débutants"},
                {(Ecosystem.OtomaiIslandCreatures, Language.FR), "Créatures de l'île d'Otomaï"},
                {(Ecosystem.Archmonsters, Language.FR), "Créatures Archi-monstres"},
                
                // English names
                {(Ecosystem.VariousCreatures, Language.EN), "Various creatures"},
                {(Ecosystem.SwampCreatures, Language.EN), "Swamp creatures"},
                {(Ecosystem.ForestCreatures, Language.EN), "Forest creatures"},
                {(Ecosystem.PlainCreatures, Language.EN), "Plain creatures"},
                {(Ecosystem.FieldCreatures, Language.EN), "Field creatures"},
                {(Ecosystem.MoorCreatures, Language.EN), "Moor creatures"},
                {(Ecosystem.MoonIslandCreatures, Language.EN), "Moon Island creatures"},
                {(Ecosystem.WabbitIslandCreatures, Language.EN), "Wabbit Island creatures"},
                {(Ecosystem.PandalaCreatures, Language.EN), "Pandala creatures"},
                {(Ecosystem.HumanoidCreatures, Language.EN), "Humanoid creatures"},
                {(Ecosystem.DarkCreatures, Language.EN), "Dark creatures"},
                {(Ecosystem.ResourcesProtectors, Language.EN), "Resource Protectors"},
                {(Ecosystem.CityCreatures, Language.EN), "City creatures"},
                {(Ecosystem.BreederVillageCreatures, Language.EN), "Breeder Village creatures"},
                {(Ecosystem.BeachCreatures, Language.EN), "Beach creatures"},
                {(Ecosystem.MinotororIslandCreatures, Language.EN), "Minotoror Island creatures"},
                {(Ecosystem.MountainCreatures, Language.EN), "Mountain creatures"},
                {(Ecosystem.BeginnerAreaCreatures, Language.EN), "Beginner Area creatures"},
                {(Ecosystem.OtomaiIslandCreatures, Language.EN), "Otomai Island creatures"},
                {(Ecosystem.Archmonsters, Language.EN), "Archmonsters"},
                
                // Spanish names
                {(Ecosystem.VariousCreatures, Language.ES), "Criaturas diversas"},
                {(Ecosystem.SwampCreatures, Language.ES), "Criaturas de los pantanos"},
                {(Ecosystem.ForestCreatures, Language.ES), "Criaturas del bosque"},
                {(Ecosystem.PlainCreatures, Language.ES), "Criaturas de las llanuras"},
                {(Ecosystem.FieldCreatures, Language.ES), "Criaturas de los campos"},
                {(Ecosystem.MoorCreatures, Language.ES), "Criaturas de las landas"},
                {(Ecosystem.MoonIslandCreatures, Language.ES), "Criaturas de la Isla de Moon"},
                {(Ecosystem.WabbitIslandCreatures, Language.ES), "Criaturas de la Isla de los Wabbits"},
                {(Ecosystem.PandalaCreatures, Language.ES), "Criaturas de Pandala"},
                {(Ecosystem.HumanoidCreatures, Language.ES), "Criaturas humanoides"},
                {(Ecosystem.DarkCreatures, Language.ES), "Criaturas de la noche"},
                {(Ecosystem.ResourcesProtectors, Language.ES), "Protectores de los recursos"},
                {(Ecosystem.CityCreatures, Language.ES), "Criaturas de las ciudades"},
                {(Ecosystem.BreederVillageCreatures, Language.ES), "Criaturas del pueblo de los ganaderos"},
                {(Ecosystem.BeachCreatures, Language.ES), "Criaturas de las playas"},
                {(Ecosystem.MinotororIslandCreatures, Language.ES), "Criaturas de la isla de Minotauroro"},
                {(Ecosystem.MountainCreatures, Language.ES), "Criaturas de la montaña"},
                {(Ecosystem.BeginnerAreaCreatures, Language.ES), "Criaturas de la zona de los novatos"},
                {(Ecosystem.OtomaiIslandCreatures, Language.ES), "Criaturas de la isla de Otomai"},
                {(Ecosystem.Archmonsters, Language.ES), "Criaturas Archi-monstruo"}
            };
        
        if (BreedNames == null || BreedNames.Count == 0)
            BreedNames = new ()
            {
                // FR names
                {(Breed.Arachnee, Language.FR), "Arakne"},
                {(Breed.Archmonsters, Language.FR), "Les Archi-monstres"},
                {(Breed.Bandits, Language.FR), "Bandits"},
                {(Breed.BeachMonsters, Language.FR), "Monstres des plages"},
                {(Breed.Blop, Language.FR), "Mulou"},
                {(Breed.Boowolf, Language.FR), "Boowolf"},
                {(Breed.Boss, Language.FR), "Boss"},
                {(Breed.BottomlessPeatBogMonsters, Language.FR), "Monstres de la Tourbière sans fond"},
                {(Breed.Bworks, Language.FR), "Bworks"},
                {(Breed.CaniaPlainMonsters, Language.FR), "Monstres des Plaines de Cania"},
                {(Breed.CaveMonsters, Language.FR), "Monstres des cavernes"},
                {(Breed.CerealProtectors, Language.FR), "Protecteurs des Céréales"},
                {(Breed.Chafers, Language.FR), "Chafers"},
                {(Breed.ClassSummonings, Language.FR), "Invocations de classe"},
                {(Breed.CoralBeachMonsters, Language.FR), "Monstres de la plage de corail"},
                {(Breed.Cracklers, Language.FR), "Craqueleurs"},
                {(Breed.Crocodyls, Language.FR), "Crocodailles"},
                {(Breed.Crows, Language.FR), "Corbacs"},
                {(Breed.DarkJungleMonsters, Language.FR), "Monstres de la Jungle Sombre"},
                {(Breed.DoppleTemple, Language.FR), "Dopeuls Temple"},
                {(Breed.DoppleVillageMonsters, Language.FR), "Monstres du Village des Dopeuls"},
                {(Breed.Dragoturkeys, Language.FR), "Dragodinde"},
                {(Breed.Dreggons, Language.FR), "Dragoeufs"},
                {(Breed.FieldMonsters, Language.FR), "Plantes des champs"},
                {(Breed.Firefoux, Language.FR), "Firefoux"},
                {(Breed.FishProtectors, Language.FR), "Protecteurs des Poissons"},
                {(Breed.FoggyCanopyMonsters, Language.FR), "Monstres de la Canopée Embrumée"},
                {(Breed.ForestAnimals, Language.FR), "Animaux de la forêt"},
                {(Breed.Ghosts, Language.FR), "Fantômes"},
                {(Breed.Gobbals, Language.FR), "Bouftous"},
                {(Breed.Goblins, Language.FR), "Gobelins"},
                {(Breed.GrassyPlainMonsters, Language.FR), "Monstres des Plaines herbeuses"},
                {(Breed.Guards, Language.FR), "Gardes"},
                {(Breed.Imps, Language.FR), "Brigandins"},
                {(Breed.Jellies, Language.FR), "Gelées"},
                {(Breed.Kitsous, Language.FR), "Kitsous"},
                {(Breed.Koalaks, Language.FR), "Koalaks"},
                {(Breed.KwakVillageGuardians, Language.FR), "Gardiens des villages de Kwaks"},
                {(Breed.Kwaks, Language.FR), "Kwaks"},
                {(Breed.KwismasMonsters, Language.FR), "Monstres de Nowel"},
                {(Breed.Larvae, Language.FR), "Larves"},
                {(Breed.Minos, Language.FR), "Minos"},
                {(Breed.MonstersFromTheBeginningArea, Language.FR), "Monstres de la zone des débutants"},
                {(Breed.MoonIslandKannibals, Language.FR), "Kannibouls de l'île de Moon"},
                {(Breed.MoonMonsters, Language.FR), "Monstres de Moon"},
                {(Breed.MoonPirates, Language.FR), "Pirates de Moon"},
                {(Breed.MoonPlants, Language.FR), "Plantes de Moon"},
                {(Breed.MoonTurtles, Language.FR), "Tortues de Moon"},
                {(Breed.MoorMonsters, Language.FR), "Monstres des landes"},
                {(Breed.Moskitos, Language.FR), "Moskitos"},
                {(Breed.Mushrooms, Language.FR), "Champignons"},
                {(Breed.NightMonsters, Language.FR), "Monstres de la nuit"},
                {(Breed.NotListed, Language.FR), "Non classé"},
                {(Breed.Npc, Language.FR), "Pnjs"},
                {(Breed.OreProtectors, Language.FR), "Protecteurs des Minerais"},
                {(Breed.OtomaiArkMonsters, Language.FR), "Monstres de l'Arche d'Otomaï"},
                {(Breed.PandalaGhost, Language.FR), "Fantôme de Pandala"},
                {(Breed.PandalaMonsters, Language.FR), "Monstres de Pandala"},
                {(Breed.PandalaPlants, Language.FR), "Plantes de Pandala"},
                {(Breed.PandalaVillageMonsters, Language.FR), "Monstres du village de Pandala"},
                {(Breed.Pandawas, Language.FR), "Pandawas"},
                {(Breed.PetGhosts, Language.FR), "Familiers Fantômes"},
                {(Breed.Pigs, Language.FR), "Cochons"},
                {(Breed.Piwis, Language.FR), "Pious"},
                {(Breed.PlantProtectors, Language.FR), "Protecteurs des Plantes"},
                {(Breed.QuestMonsters, Language.FR), "Monstres de quête"},
                {(Breed.Scaraleaf, Language.FR), "Scarafeuille"},
                {(Breed.SewerMonsters, Language.FR), "Monstre des égouts"},
                {(Breed.SwampMonsters, Language.FR), "Monstres des marécages"},
                {(Breed.TerritoryQuestMonsters, Language.FR), "Monstres des conquêtes de territoires"},
                {(Breed.Tofus, Language.FR), "Tofus"},
                {(Breed.TreeKeeholoMonsters, Language.FR), "Monstres de l'Arbre Hakam"},
                {(Breed.TreeProtectors, Language.FR), "Protecteurs des Arbres"},
                {(Breed.Treechnidian, Language.FR), "Treechnidian"},
                {(Breed.TutorialMonsters, Language.FR), "Monstres Tutorial"},
                {(Breed.Wabbits, Language.FR), "Wabbits"},
                {(Breed.Wanted, Language.FR), "Avis de recherche"},
                
                // English names
                {(Breed.Arachnee, Language.EN), "Arachnee"},
                {(Breed.Archmonsters, Language.EN), "Archmonsters"},
                {(Breed.Bandits, Language.EN), "Bandits"},
                {(Breed.BeachMonsters, Language.EN), "Beach Monsters"},
                {(Breed.Blop, Language.EN), "Blop"},
                {(Breed.Boowolf, Language.EN), "Boowolf"},
                {(Breed.Boss, Language.EN), "Boss"},
                {(Breed.BottomlessPeatBogMonsters, Language.EN), "Bottomless Peat Bog Monsters"},
                {(Breed.Bworks, Language.EN), "Bworks"},
                {(Breed.CaniaPlainMonsters, Language.EN), "Cania Plain Monsters"},
                {(Breed.CaveMonsters, Language.EN), "Cave Monsters"},
                {(Breed.CerealProtectors, Language.EN), "Cereal Protectors"},
                {(Breed.Chafers, Language.EN), "Chafers"},
                {(Breed.ClassSummonings, Language.EN), "Class Summonings"},
                {(Breed.CoralBeachMonsters, Language.EN), "Coral Beach Monsters"},
                {(Breed.Cracklers, Language.EN), "Cracklers"},
                {(Breed.Crocodyls, Language.EN), "Crocodyls"},
                {(Breed.Crows, Language.EN), "Crows"},
                {(Breed.DarkJungleMonsters, Language.EN), "Dark Jungle Monsters"},
                {(Breed.DoppleTemple, Language.EN), "Dopple Temple"},
                {(Breed.DoppleVillageMonsters, Language.EN), "Dopple Village Monsters"},
                {(Breed.Dragoturkeys, Language.EN), "Dragoturkey"},
                {(Breed.Dreggons, Language.EN), "Dreggons"},
                {(Breed.FieldMonsters, Language.EN), "Field Monsters"},
                {(Breed.Firefoux, Language.EN), "Firefoux"},
                {(Breed.FishProtectors, Language.EN), "Fish Protectors"},
                {(Breed.FoggyCanopyMonsters, Language.EN), "Foggy Canopy Monsters"},
                {(Breed.ForestAnimals, Language.EN), "Forest animals"},
                {(Breed.Ghosts, Language.EN), "Ghosts"},
                {(Breed.Gobbals, Language.EN), "Gobballs"},
                {(Breed.Goblins, Language.EN), "Goblins"},
                {(Breed.GrassyPlainMonsters, Language.EN), "Grassy Plain Monsters"},
                {(Breed.Guards, Language.EN), "Guards"},
                {(Breed.Imps, Language.EN), "Imps"},
                {(Breed.Jellies, Language.EN), "Jellies"},
                {(Breed.Kitsous, Language.EN), "Kitsous"},
                {(Breed.Koalaks, Language.EN), "Koalaks"},
                {(Breed.KwakVillageGuardians, Language.EN), "Kwak Villages Guardians"},
                {(Breed.Kwaks, Language.EN), "Kwaks"},
                {(Breed.KwismasMonsters, Language.EN), "Kwismas Monsters"},
                {(Breed.Larvae, Language.EN), "Larvae"},
                {(Breed.Minos, Language.EN), "Minos"},
                {(Breed.MonstersFromTheBeginningArea, Language.EN), "Monsters from the Beginner Area"},
                {(Breed.MoonIslandKannibals, Language.EN), "Moon Island Kanniballs"},
                {(Breed.MoonMonsters, Language.EN), "Moon Monsters"},
                {(Breed.MoonPirates, Language.EN), "Moon Pirates"},
                {(Breed.MoonPlants, Language.EN), "Moon Plants"},
                {(Breed.MoonTurtles, Language.EN), "Moon Turtles"},
                {(Breed.MoorMonsters, Language.EN), "Moor Monsters"},
                {(Breed.Moskitos, Language.EN), "Moskitos"},
                {(Breed.Mushrooms, Language.EN), "Mushrooms"},
                {(Breed.NightMonsters, Language.EN), "Night Monsters"},
                {(Breed.NotListed, Language.EN), "Not Listed"},
                {(Breed.Npc, Language.EN), "NPCs"},
                {(Breed.OreProtectors, Language.EN), "Ore Protectors"},
                {(Breed.OtomaiArkMonsters, Language.EN), "Otomai's Ark Monsters"},
                {(Breed.PandalaGhost, Language.EN), "Pandala Ghost"},
                {(Breed.PandalaMonsters, Language.EN), "Pandala Monsters"},
                {(Breed.PandalaPlants, Language.EN), "Pandala Plants"},
                {(Breed.PandalaVillageMonsters, Language.EN), "Pandala Village Monsters"},
                {(Breed.Pandawas, Language.EN), "Pandawas"},
                {(Breed.PetGhosts, Language.EN), "Pet Ghosts"},
                {(Breed.Pigs, Language.EN), "Pigs"},
                {(Breed.Piwis, Language.EN), "Piwis"},
                {(Breed.PlantProtectors, Language.EN), "Plant Protectors"},
                {(Breed.QuestMonsters, Language.EN), "Quest Monsters"},
                {(Breed.Scaraleaf, Language.EN), "Scaraleaf"},
                {(Breed.SewerMonsters, Language.EN), "Sewers Monsters"},
                {(Breed.SwampMonsters, Language.EN), "Swamp Monsters"},
                {(Breed.TerritoryQuestMonsters, Language.EN), "Territory Quest Monsters"},
                {(Breed.Tofus, Language.EN), "Tofus"},
                {(Breed.TreeKeeholoMonsters, Language.EN), "Tree Keeholo Monsters"},
                {(Breed.TreeProtectors, Language.EN), "Tree Protectors"},
                {(Breed.Treechnidian, Language.EN), "Treechnidian"},
                {(Breed.TutorialMonsters, Language.EN), "Tutorial Monsters"},
                {(Breed.Wabbits, Language.EN), "Wabbits"},
                {(Breed.Wanted, Language.EN), "Wanted"},
                
                // Spanish names
                {(Breed.Arachnee, Language.ES), "Arakna"},
                {(Breed.Archmonsters, Language.ES), "Los Archi-monstruos"},
                {(Breed.Bandits, Language.ES), "Bandidos"},
                {(Breed.BeachMonsters, Language.ES), "Monstruos de las playas"},
                {(Breed.Blop, Language.ES), "Milubo"},
                {(Breed.Boowolf, Language.ES), "Boowolf"},
                {(Breed.Boss, Language.ES), "Jefe final"},
                {(Breed.BottomlessPeatBogMonsters, Language.ES), "Monstruos de la Turbera sin fondo"},
                {(Breed.Bworks, Language.ES), "Bworks"},
                {(Breed.CaniaPlainMonsters, Language.ES), "Monstruos de las Llanuras de Cania"},
                {(Breed.CaveMonsters, Language.ES), "Monstruos de las cuevas"},
                {(Breed.CerealProtectors, Language.ES), "Protectores de los cereales"},
                {(Breed.Chafers, Language.ES), "Chafers"},
                {(Breed.ClassSummonings, Language.ES), "Invocaciones de clase"},
                {(Breed.CoralBeachMonsters, Language.ES), "Monstruos de la playa de coral"},
                {(Breed.Cracklers, Language.ES), "Crujidores"},
                {(Breed.Crocodyls, Language.ES), "Cocodrails"},
                {(Breed.Crows, Language.ES), "Cuerboks"},
                {(Breed.DarkJungleMonsters, Language.ES), "Monstruos de la Oscura Selva"},
                {(Breed.DoppleTemple, Language.ES), "Dopeuls Templo"},
                {(Breed.DoppleVillageMonsters, Language.ES), "Monstruos del Pueblo de los Dopeuls"},
                {(Breed.Dragoturkeys, Language.ES), "Dragopavo"},
                {(Breed.Dreggons, Language.ES), "Dragohuevos"},
                {(Breed.FieldMonsters, Language.ES), "Plantas de los campos"},
                {(Breed.Firefoux, Language.ES), "Firefux"},
                {(Breed.FishProtectors, Language.ES), "Protectores de los Peces"},
                {(Breed.FoggyCanopyMonsters, Language.ES), "Monstruos de la Canopea de las Nieblas"},
                {(Breed.ForestAnimals, Language.ES), "Animales del bosque"},
                {(Breed.Ghosts, Language.ES), "Fantasmas"},
                {(Breed.Gobbals, Language.ES), "Blops"},
                {(Breed.Goblins, Language.ES), "Goblins"},
                {(Breed.GrassyPlainMonsters, Language.ES), "Monstruos de las Llanuras herbosas"},
                {(Breed.Guards, Language.ES), "Guardias"},
                {(Breed.Imps, Language.ES), "Salteadorillos"},
                {(Breed.Jellies, Language.ES), "Gelatinas"},
                {(Breed.Kitsous, Language.ES), "Kitsus"},
                {(Breed.Koalaks, Language.ES), "Koalaks"},
                {(Breed.KwakVillageGuardians, Language.ES), "Guardianes de los pueblos de Kwaks"},
                {(Breed.Kwaks, Language.ES), "Kwaks"},
                {(Breed.KwismasMonsters, Language.ES), "Monstruos de Nawidad"},
                {(Breed.Larvae, Language.ES), "Larvas"},
                {(Breed.Minos, Language.ES), "Minos"},
                {(Breed.MonstersFromTheBeginningArea, Language.ES), "Monstruos de la zona de novatos"},
                {(Breed.MoonIslandKannibals, Language.ES), "Kaníbolas de la Isla de Moon"},
                {(Breed.MoonMonsters, Language.ES), "Monstruos de Moon"},
                {(Breed.MoonPirates, Language.ES), "Piratas de Moon"},
                {(Breed.MoonPlants, Language.ES), "Plantas de Moon"},
                {(Breed.MoonTurtles, Language.ES), "Tortugas de Moon"},
                {(Breed.MoorMonsters, Language.ES), "Monstruos de las landas"},
                {(Breed.Moskitos, Language.ES), "Moskitos"},
                {(Breed.Mushrooms, Language.ES), "Setas"},
                {(Breed.NightMonsters, Language.ES), "Monstruos de la noche"},
                {(Breed.NotListed, Language.ES), "Sin clasificar"},
                {(Breed.Npc, Language.ES), "Pnjs"},
                {(Breed.OreProtectors, Language.ES), "Protectores de los Minerales"},
                {(Breed.OtomaiArkMonsters, Language.ES), "Monstruos del Arca de Otomai"},
                {(Breed.PandalaGhost, Language.ES), "Fantasma de Pandala"},
                {(Breed.PandalaMonsters, Language.ES), "Monstruos de Pandala"},
                {(Breed.PandalaPlants, Language.ES), "Plantas de Pandala"},
                {(Breed.PandalaVillageMonsters, Language.ES), "Monstruos del pueblo de Pandala"},
                {(Breed.Pandawas, Language.ES), "Pandawas"},
                {(Breed.PetGhosts, Language.ES), "Mascotas Fantasmas"},
                {(Breed.Pigs, Language.ES), "Cerdos"},
                {(Breed.Piwis, Language.ES), "Jalatós"},
                {(Breed.PlantProtectors, Language.ES), "Protectores de las Plantas"},
                {(Breed.QuestMonsters, Language.ES), "Monstruos de búsqueda"},
                {(Breed.Scaraleaf, Language.ES), "Escarahoja"},
                {(Breed.SewerMonsters, Language.ES), "Monstruo de las alcantarillas"},
                {(Breed.SwampMonsters, Language.ES), "Monstruos de los pantanos"},
                {(Breed.TerritoryQuestMonsters, Language.ES), "Monstruos de las conquistas de territorios"},
                {(Breed.Tofus, Language.ES), "Tofus"},
                {(Breed.TreeKeeholoMonsters, Language.ES), "Monstruos del Árbol Hakam"},
                {(Breed.TreeProtectors, Language.ES), "Protectores de los árboles"},
                {(Breed.Treechnidian, Language.ES), "Treechnidian"},
                {(Breed.TutorialMonsters, Language.ES), "Monstruos Tutorial"},
                {(Breed.Wabbits, Language.ES), "Wabbits"},
                {(Breed.Wanted, Language.ES), "Se busca"}
            };
    }

    public static Dictionary<(EquipmentType, Language), string>? EquipmentTypeNames { get; }

    public static Dictionary<(ConsumableType, Language), string>? ConsumableTypeNames { get; }

    public static Dictionary<(ResourceType, Language), string>? ResourceTypeNames { get; }
    
    public static Dictionary<(Ecosystem, Language), string>? EcosystemNames { get; }

    public static Dictionary<(Breed, Language), string>? BreedNames { get; }
    
    // public static Dictionary<(SubArea, Language), string> SubAreaNames = new()
    // {
    //     // English names
    //     {(SubArea.TheZothDoorKeepers, Language.EN), "The Zoth Door Keepers"},
    //     {(SubArea.SkeunkHideout, Language.EN), "Skeunk Hideout"},
    //     {(SubArea.AbandonedRailway, Language.EN), "Abandoned Railway"},
    //     {(SubArea.AerdalaPrism, Language.EN), "Aerdala Prism"},
    //     {(SubArea.AgonyVhelley, Language.EN), "Agony Valley"},
    //     {(SubArea.AkwadalaPrism, Language.EN), "Akwadala Prism"},
    //     {(SubArea.Amakna, Language.EN), "Amakna"},
    //     {(SubArea.AmaknaCastleGobbalBreedingStation, Language.EN), "Amakna Castle Gobbal Breeding Station"},
    //     {(SubArea.AmanknaCastleRatDungeon, Language.EN), "Amakna Castle Rat Dungeon"},
    //     {(SubArea.AmaknaCastleTunnel, Language.EN), "Amakna Castle Tunnel"},
    //     {(SubArea.AsseCoast, Language.EN), "Asse Coast"},
    //     {(SubArea.AstrubCity, Language.EN), "Astrub City"},
    //     {(SubArea.AstrubDeepTunnel, Language.EN), "Astrub Deep Tunnel"},
    //     {(SubArea.AstrubFields, Language.EN), "Astrub Fields"},
    //     {(SubArea.AstrubForest, Language.EN), "Astrub Forest"}, 
    //     {(SubArea.AstrubMeadows, Language.EN), "Astrub Meadows"},
    //     {(SubArea.AstrubMines, Language.EN), "Astrub Mines"},
    //     {(SubArea.AstrubRockyInlet, Language.EN), "Astrub Rocky Inlet"},
    //     {(SubArea.AstrubTunnel, Language.EN), "Astrub Tunnel"},
    //     {(SubArea.BakersQuarter, Language.EN), "Baker's Quarter"},
    //     {(SubArea.BanditTerritory, Language.EN), "Bandit Territory"},
    //     {(SubArea.BherbsGully, Language.EN), "Bherb's Gully"},
    //     {(SubArea.BlopDungeon, Language.EN), "Blop Dungeon"},
    //     {(SubArea.Bonta, Language.EN), "Bonta"},
    //     {(SubArea.BontaCemetery, Language.EN), "Bonta Cemetery"},
    //     {(SubArea.BontaRatDungeon, Language.EN), "Bonta Rat Dungeon"},
    //     {(SubArea.BontaSewers, Language.EN), "Bonta Sewers"},
    //     {(SubArea.BorderOfAerdala, Language.EN), "Border of Aerdala"},
    //     {(SubArea.BorderOfAkwadala, Language.EN), "Border of Akwadala"},
    //     {(SubArea.BorderOfFeudala, Language.EN), "Border of Feudala"},
    //     {(SubArea.BorderOfTerrdala, Language.EN), "Border of Terrdala"},
    //     {(SubArea.BottomlessPeatBog, Language.EN), "Bottomless Peat Bog"},
    //     {(SubArea.BottomlessSwamps, Language.EN), "Bottomless Swamps"},
    //     {(SubArea.Brakmar, Language.EN), "Brakmar"},
    //     {(SubArea.BrakmarFrontage, Language.EN), "Brakmar Frontage"},
    //     {(SubArea.BrakmarRatDungen, Language.EN), "Brakmar Rat Dungeon"},
    //     {(SubArea.BrakmarSewers, Language.EN), "Brakmar Sewers"},
    //     {(SubArea.BrouceBoulgourgsClearing, Language.EN), "Brouce Boulgourgs Clearing"},
    //     {(SubArea.ButchersQuarter, Language.EN), "Butcher's Quarter"},
    //     {(SubArea.BworkDungeon, Language.EN), "Bwork Dungeon"},
    //     {(SubArea.CampOfTheOneArmedBandits, Language.EN), "Camp of the One-Armed Bandits"},
    //     {(SubArea.CaniaBay, Language.EN), "Cania Bay"},
    //     {(SubArea.CaniaForest, Language.EN), "Cania Forest"},
    //     {(SubArea.CaniaMassif, Language.EN), "Cania Massif"},
    //     {(SubArea.CaniaPlain, Language.EN), "Cania Plain"},
    //     {(SubArea.Canidae, Language.EN), "Canidae"},
    //     {(SubArea.CastawaysIsland, Language.EN), "Castaway's Island"},
    //     {(SubArea.CemeteryOfHeroes, Language.EN), "Cemetery of Heroes"},
    //     {(SubArea.CemeteryOfTheTortured, Language.EN), "Cemetery of the Tortured"},
    //     {(SubArea.CooralBeach, Language.EN), "Cooral Beach"},
    //     {(SubArea.CracklerDungeon, Language.EN), "Crackler Dungeon"},
    //     {(SubArea.CracklerMountain, Language.EN), "Crackler Mountain"},
    //     {(SubArea.DarkJungle, Language.EN), "Dark Jungle"},
    //     {(SubArea.DarkTreechnidForest, Language.EN), "Dark Treechnid Forest"},
    //     {(SubArea.DopplePrism, Language.EN), "Dopple Prism"},
    //     {(SubArea.DoppleTraining, Language.EN), "Dopple Training"},
    //     {(SubArea.DoppleVillage, Language.EN), "Dopple Village"},
    //     {(SubArea.DreggonTunnel, Language.EN), "Dreggon Tunnel"},
    //     {(SubArea.DreggonVillage, Language.EN), "Dreggon Village"},
    //     {(SubArea.EdgeOfBonta, Language.EN), "Edge of Bonta"},
    //     {(SubArea.EdgeOfTheEvilForest, Language.EN), "Edge of the Evil Forest"},
    //     {(SubArea.EdgeOfTheMilicluster, Language.EN), "Edge of the Milicluster"},
    //     {(SubArea.EdgeOfTheTreechnidForest, Language.EN), "Edge of the Treechnid Forest"},
    //     {(SubArea.EltnegWood, Language.EN), "Eltneg Wood"},
    //     {(SubArea.EnchantedLakes, Language.EN), "Enchanted Lakes"},
    //     {(SubArea.FeudalaPrism, Language.EN), "Feudala Prism"},
    //     {(SubArea.FeudalaVillage, Language.EN), "Feudala Village"},
    //     {(SubArea.FieldDungeon, Language.EN), "Field Dungeon"},
    //     {(SubArea.FirefouxDungeon, Language.EN), "Firefoux Dungeon"},
    //     {(SubArea.FortificationOfBonta, Language.EN), "Fortification of Bonta"},
    //     {(SubArea.FungusCavern, Language.EN), "Fungus Cavern"},
    //     {(SubArea.FungusDungeon, Language.EN), "Fungus Dungeon"},
    //     {(SubArea.GisgoulTheDevastatedVillage, Language.EN), "Gisgoul The Devastated Village"},
    //     {(SubArea.GobballCorner, Language.EN), "Gobball Corner"},
    //     {(SubArea.GobballDungeon, Language.EN), "Gobball Dungeon"},
    //     {(SubArea.GrassPlains, Language.EN), "Grass Plains"},
    //     {(SubArea.GrottoHesque, Language.EN), "Grotto Hesque"},
    //     {(SubArea.HandymensQuarter, Language.EN), "Handymen's Quarter"},
    //     {(SubArea.HiddenLaboratory, Language.EN), "Hidden Laboratory"},
    //     {(SubArea.HoldOfOtomaisArk, Language.EN), "Hold of Otomai's Ark"},
    //     {(SubArea.IlyzaellesLookout, Language.EN), "Ilyzaelle's Lookout"},
    //     {(SubArea.ImpPrism, Language.EN), "Imp Prism"},
    //     {(SubArea.ImpVillage, Language.EN), "Imp Village"},
    //     {(SubArea.JewellersQuarter, Language.EN), "Jeweller's Quarter"},
    //     {(SubArea.KaliptusForest, Language.EN), "Kaliptus Forest"},
    //     {(SubArea.KawaiiRiver, Language.EN), "Kawaii River"},
    //     {(SubArea.KimbosCanopy, Language.EN), "Kimbo's Canopy"},
    //     {(SubArea.KitsouDungeon, Language.EN), "Kitsou Dungeon"},
    //     {(SubArea.KoolichCavern, Language.EN), "Koolich Cavern"},
    //     {(SubArea.KwismasDeungeon, Language.EN), "Kwismas Dungeon"},
    //     {(SubArea.KwismasIsland, Language.EN), "Kwismas Island"},
    //     {(SubArea.LabyrinthOfTheMinotoror, Language.EN), "Labyrinth of the Minotoror"},
    //     {(SubArea.Lake, Language.EN), "Lake"},
    //     {(SubArea.LarvaDungeon, Language.EN), "Larva Dungeon"},
    //     {(SubArea.LittleSlopeGrove, Language.EN), "Little Slope Grove"},
    //     {(SubArea.LordCrowsLibrary, Language.EN), "Lord Crow's Library"},
    //     {(SubArea.LousyPigPlain, Language.EN), "Lousy Pig Plain"},
    //     {(SubArea.LowCracklerMountain, Language.EN), "Low Crackler Mountain"},
    //     {(SubArea.LumberjacksQuarter, Language.EN), "Lumberjack's Quarter"},
    //     {(SubArea.MadrestamHarbour, Language.EN), "Madrestam Harbour"},
    //     {(SubArea.MilitiaDistrict, Language.EN), "Militia District"},
    //     {(SubArea.MinotororIsland, Language.EN), "Minotoror Island"},
    //     {(SubArea.MoonBeach, Language.EN), "Moon Beach"},
    //     {(SubArea.MushdCorner, Language.EN), "Mushd Corner"},
    //     {(SubArea.MysteriousTunnel, Language.EN), "Mysterious Tunnel"},
    //     {(SubArea.NauseatingSwamps, Language.EN), "Nauseating Swamps"},
    //     {(SubArea.NeutralPandala, Language.EN), "Neutral Pandala"},
    //     {(SubArea.NolifisIsland, Language.EN), "Nolifis Island"},
    //     {(SubArea.OtomaisArk, Language.EN), "Otomai's Ark"},
    //     {(SubArea.PandalaForest, Language.EN), "Pandala Forest"},
    //     {(SubArea.PandalaVillage, Language.EN), "Pandala Village"},
    //     {(SubArea.PandikazeHideout, Language.EN), "Pandikaze Hideout"},
    //     {(SubArea.PassageToBrakmar, Language.EN), "Passage to Brakmar"},
    //     {(SubArea.PorcoTerritory, Language.EN), "Porco Territory"},
    //     {(SubArea.PrimitiveCemetery, Language.EN), "Primitive Cemetery"},
    //     {(SubArea.PutridPeatBog, Language.EN), "Putrid Peat Bog"},
    //     {(SubArea.QuTansSanctuary, Language.EN), "Qu'Tan's Sanctuary"},
    //     {(SubArea.RoadToBonta, Language.EN), "Road to Bonta"},
    //     {(SubArea.RockyPeaks, Language.EN), "Rocky Peaks"},
    //     {(SubArea.RockyPlains, Language.EN), "Rocky Plains"},
    //     {(SubArea.SandDungeon, Language.EN), "Sand Dungeon"},
    //     {(SubArea.ScaraleafDungeon, Language.EN), "Scaraleaf Dungeon"},
    //     {(SubArea.Sea, Language.EN), "Sea"},
    //     {(SubArea.SidimoteMoor, Language.EN), "Sidimote Moor"},
    //     {(SubArea.SkeletonWabbitIsland, Language.EN), "Skeleton Wabbit Island"},
    //     {(SubArea.SmallWabbitIsland, Language.EN), "Small Wabbit Island"},
    //     {(SubArea.SmithsQuarter, Language.EN), "Smith's Quarter"},
    //     {(SubArea.Sufokia, Language.EN), "Sufokia"},
    //     {(SubArea.SufokianGulfShoreline, Language.EN), "Sufokian Gulf Shoreline"},
    //     {(SubArea.SurroundingsOfAstrub, Language.EN), "Surroundings of Astrub"},
    //     {(SubArea.TailorsQuarter, Language.EN), "Tailor's Quarter"},
    //     {(SubArea.Tainela, Language.EN), "Tainela"},
    //     {(SubArea.TerrdalaPrism, Language.EN), "Terrdala Prism"},
    //     {(SubArea.TheAmaknaForest, Language.EN), "The Amakna Forest"},
    //     {(SubArea.TheBworkCamp, Language.EN), "The Bwork Camp"},
    //     {(SubArea.TheCaniaFields, Language.EN), "The Cania Fields"},
    //     {(SubArea.TheCemetery, Language.EN), "The Cemetery"},
    //     {(SubArea.TheCountryside, Language.EN), "The Countryside"},
    //     {(SubArea.TheCradle, Language.EN), "The Cradle"},
    //     {(SubArea.TheCrowdDomain, Language.EN), "The Crowd Domain"},
    //     {(SubArea.TheCrypts, Language.EN), "The Crypts"},
    //     {(SubArea.TheDeepMoonJungle, Language.EN), "The Deep Moon Jungle"},
    //     {(SubArea.TheDragonPigsMaze, Language.EN), "The Dragon Pig's Maze"},
    //     {(SubArea.TheDreggonPeninsula, Language.EN), "The Dreggon Peninsula"},
    //     {(SubArea.TheDreggonsSanctuary, Language.EN), "The Dreggons Sanctuary"},
    //     {(SubArea.TheEvilForest, Language.EN), "The Evil Forest"},
    //     {(SubArea.TheGoblinCamp, Language.EN), "The Goblin Camp"},
    //     {(SubArea.TheIngalssesFields, Language.EN), "The Ingalsses Fields"},
    //     {(SubArea.TheJellyPeninsula, Language.EN), "The Jelly Peninsula"},
    //     {(SubArea.TheMilicluster, Language.EN), "The Milicluster"},
    //     {(SubArea.ThePirateBoat, Language.EN), "The Pirate Boat"},
    //     {(SubArea.TheRoadToMoon, Language.EN), "The Road to Moon"},
    //     {(SubArea.TheSwamp, Language.EN), "The Swamp"},
    //     {(SubArea.TheTempleOfCra, Language.EN), "The Temple of Cra"},
    //     {(SubArea.TheTempleOfEcaflip, Language.EN), "The Temple of Ecaflip"},
    //     {(SubArea.TheTempleOfEniripsa, Language.EN), "The Temple of Eniripsa"},
    //     {(SubArea.TheTempleOfEnutrof, Language.EN), "The Temple of Enutrof"},
    //     {(SubArea.TheTempleOfFeca, Language.EN), "The Temple of Feca"},
    //     {(SubArea.TheTempleOfIop, Language.EN), "The Temple of Iop"},
    //     {(SubArea.TheTempleOfPandawa, Language.EN), "The Temple of Pandawa"},
    //     {(SubArea.TheTempleOfOsamodas, Language.EN), "The Temple of Osamodas"},
    //     {(SubArea.TheTempleOfSacrier, Language.EN), "The Temple of Sacrier"},
    //     {(SubArea.TheTempleOfSadida, Language.EN), "The Temple of Sadida"},
    //     {(SubArea.TheTempleOfSram, Language.EN), "The Temple of Sram"},
    //     {(SubArea.TheTempleOfXelor, Language.EN), "The Temple of Xelor"},
    //     {(SubArea.TheTerritoryOfTheBandits, Language.EN), "The Territory of the Bandits"},
    //     {(SubArea.TheVillage, Language.EN), "The Village"},
    //     {(SubArea.TofuCorner, Language.EN), "Tofu Corner"},
    //     {(SubArea.TofuDungeon, Language.EN), "Tofu Dungeon"},
    //     {(SubArea.TreeKeeholoVillage, Language.EN), "Tree Keeholo Village"},
    //     {(SubArea.TreeKeeholoTrunk, Language.EN), "Tree Keeholo Trunk"},
    //     {(SubArea.TreechnidDungeon, Language.EN), "Treechnid Dungeon"},
    //     {(SubArea.TreechnidForest, Language.EN), "Treechnid Forest"},
    //     {(SubArea.Tunnel, Language.EN), "Tunnel"},
    //     {(SubArea.TynrilLaboratory, Language.EN), "Tynril Laboratory"},
    //     {(SubArea.WabbitCastleIsland, Language.EN), "Wabbit Castle Island"},
    //     {(SubArea.WabbitCastle, Language.EN), "Wabbit Castle"},
    //     {(SubArea.WabbitTunnels, Language.EN), "Wabbit Tunnels"},
    //     {(SubArea.WildCanyon, Language.EN), "Wild Canyon"},
    //     {(SubArea.WildDragoturkeyTerritory, Language.EN), "Wild Dragoturkey Territory"},
    //     {(SubArea.ZothPrism, Language.EN), "Zoth Prism"},
    //     {(SubArea.ZothVillage, Language.EN), "Zoth Village"},
    // };
}