using ClassLibrary.Enums.Alignments;
using ClassLibrary.Enums.Classes;
using ClassLibrary.Enums.Effects;
using ClassLibrary.Enums.Genders;
using ClassLibrary.Enums.ItemConditions;
using ClassLibrary.Enums.Languages;
using DofusRetroAPI.Entities.Items;
using DofusRetroAPI.Entities.Items.Cards;
using DofusRetroAPI.Entities.Monsters.Breeds;
using DofusRetroAPI.Entities.Monsters.Ecosystems;

namespace DofusRetroAPI.Localization;

public static class LocalizedStrings
{
    static LocalizedStrings()
    {
        if (ItemTypeNames == null || ItemTypeNames.Count == 0)
            ItemTypeNames = new ()
            {
                // FR Localization
                {(ItemType.Amulet, Language.FR), "Amulette"},
                {(ItemType.Bow, Language.FR), "Arc"},
                {(ItemType.Wand, Language.FR), "Baguette"},
                {(ItemType.Staff, Language.FR), "Bâton"},
                {(ItemType.Dagger, Language.FR), "Dague"},
                {(ItemType.Sword, Language.FR), "Épée"},
                {(ItemType.Hammer, Language.FR), "Marteau"},
                {(ItemType.Shovel, Language.FR), "Pelle"},
                {(ItemType.Ring, Language.FR), "Anneau"},
                {(ItemType.Belt, Language.FR), "Ceinture"},
                {(ItemType.Boots, Language.FR), "Botte"},
                {(ItemType.Potion, Language.FR), "Potion"},
                {(ItemType.ExperienceScroll, Language.FR), "Parchemin d'expérience"},
                {(ItemType.GiftItem, Language.FR), "Objet de dons"},
                {(ItemType.Resource, Language.FR), "Ressource"},
                {(ItemType.Hat, Language.FR), "Chapeau"},
                {(ItemType.Cloak, Language.FR), "Cape"},
                {(ItemType.Pet, Language.FR), "Familier"},
                {(ItemType.Axe, Language.FR), "Hache"},
                {(ItemType.Tool, Language.FR), "Outil"},
                {(ItemType.Pickaxe, Language.FR), "Pioche"},
                {(ItemType.Scythe, Language.FR), "Faux"},
                {(ItemType.Dofus, Language.FR), "Dofus"},
                {(ItemType.QuestItem, Language.FR), "Objet de Quête"},
                {(ItemType.Document, Language.FR), "Document"},
                {(ItemType.SmithmagicPotion, Language.FR), "Potion de forgemagie"},
                {(ItemType.MutationItem, Language.FR), "Objet de Mutation"},
                {(ItemType.BoostFood, Language.FR), "Nourriture boost"},
                {(ItemType.Blessing, Language.FR), "Bénédiction"},
                {(ItemType.Curse, Language.FR), "Malédiction"},
                {(ItemType.RoleplayBuff, Language.FR), "Roleplay Buffs"},
                {(ItemType.FollowingCharacter, Language.FR), "Personnage suiveur"},
                {(ItemType.Bread, Language.FR), "Pain"},
                {(ItemType.Cereal, Language.FR), "Céréale"},
                {(ItemType.Flower, Language.FR), "Fleur"},
                {(ItemType.Plant, Language.FR), "Plante"},
                {(ItemType.Beer, Language.FR), "Bière"},
                {(ItemType.Wood, Language.FR), "Bois"},
                {(ItemType.Ore, Language.FR), "Minerai"},
                {(ItemType.Alloy, Language.FR), "Alliage"},
                {(ItemType.Fish, Language.FR), "Poisson"},
                {(ItemType.Candy, Language.FR), "Friandise"},
                {(ItemType.ForgetfulnessPotion, Language.FR), "Potion d'oubli de sort"},
                {(ItemType.UnlearningPotionForProfession, Language.FR), "Potion d'oubli de métier"},
                {(ItemType.SkillLossPotion, Language.FR), "Potion d'oubli de maîtrise"},
                {(ItemType.Fruit, Language.FR), "Fruit"},
                {(ItemType.Bone, Language.FR), "Os"},
                {(ItemType.Powder, Language.FR), "Poudre"},
                {(ItemType.EdibleFish, Language.FR), "Poisson comestible"},
                {(ItemType.PreciousStone, Language.FR), "Pierre précieuse"},
                {(ItemType.Stone, Language.FR), "Pierre brute"},
                {(ItemType.Flour, Language.FR), "Farine"},
                {(ItemType.Feather, Language.FR), "Plume"},
                {(ItemType.Hair, Language.FR), "Poil"},
                {(ItemType.Fabric, Language.FR), "Etoffe"},
                {(ItemType.Leather, Language.FR), "Cuir"},
                {(ItemType.Wool, Language.FR), "Laine"},
                {(ItemType.Seed, Language.FR), "Graine"},
                {(ItemType.Skin, Language.FR), "Peau"},
                {(ItemType.Oil, Language.FR), "Huile"},
                {(ItemType.StuffedAnimal, Language.FR), "Peluche"},
                {(ItemType.GuttedFish, Language.FR), "Poisson vidé"},
                {(ItemType.Meat, Language.FR), "Viande"},
                {(ItemType.PreservedMeat, Language.FR), "Viande conservée"},
                {(ItemType.Tail, Language.FR), "Queue"},
                {(ItemType.Metaria, Language.FR), "Metaria"},
                {(ItemType.Vegetable, Language.FR), "Légume"},
                {(ItemType.EdibleMeat, Language.FR), "Viande comestible"},
                {(ItemType.Dyeing, Language.FR), "Teinture"},
                {(ItemType.AlchemyEquipment, Language.FR), "Matériel d'alchimie"},
                {(ItemType.PetEgg, Language.FR), "Oeuf de familier"},
                {(ItemType.Skill, Language.FR), "Maîtrise"},
                {(ItemType.Fairywork, Language.FR), "Fée d'artifice"},
                {(ItemType.SpellScroll, Language.FR), "Parchemin de sort"},
                {(ItemType.CharacteristicScroll, Language.FR), "Parchemin de caractéristique"},
                {(ItemType.BowKennelCertificate, Language.FR), "Certificat de mise en chanil"},
                {(ItemType.SmithmagicRune, Language.FR), "Rune de forgemagie"},
                {(ItemType.Drink, Language.FR), "Boisson"},
                {(ItemType.MissionItem, Language.FR), "Objet de mission"},
                {(ItemType.Backpack, Language.FR), "Sac à dos"},
                {(ItemType.Shield, Language.FR), "Bouclier"},
                {(ItemType.SoulStone, Language.FR), "Pierre d'âme"},
                {(ItemType.Keys, Language.FR), "Clefs"},
                {(ItemType.FullSoulStone, Language.FR), "Pierre d'âme pleine"},
                {(ItemType.ForgetfulnessPotionForCollectors, Language.FR), "Potion d'oubli percepteur"},
                {(ItemType.SeekerScroll, Language.FR), "Parchemin de recherche"},
                {(ItemType.MagicStone, Language.FR), "Pierre magique"},
                {(ItemType.Gifts, Language.FR), "Cadeaux"},
                {(ItemType.PetGhost, Language.FR), "Fantôme de Familier"},
                {(ItemType.Dragoturkey, Language.FR), "Dragodinde"},
                {(ItemType.Gobball, Language.FR), "Bouftou"},
                {(ItemType.BreedingItem, Language.FR), "Objet d'élevage"},
                {(ItemType.UsableItem, Language.FR), "Objet utilisable"},
                {(ItemType.Plank, Language.FR), "Planche"},
                {(ItemType.Bark, Language.FR), "Ecorce"},
                {(ItemType.MountCertificate, Language.FR), "Certificat de monture"},
                {(ItemType.Root, Language.FR), "Racine"},
                {(ItemType.CapturingNet, Language.FR), "Filet de capture"},
                {(ItemType.BagOfResources, Language.FR), "Sac de ressources"},
                {(ItemType.Crossbow, Language.FR), "Arbalète"},
                {(ItemType.Leg, Language.FR), "Patte"},
                {(ItemType.Wing, Language.FR), "Aile"},
                {(ItemType.Egg, Language.FR), "Oeuf"},
                {(ItemType.Ear, Language.FR), "Oreille"},
                {(ItemType.Carapace, Language.FR), "Carapace"},
                {(ItemType.Bud, Language.FR), "Bourgeon"},
                {(ItemType.Eye, Language.FR), "Oeil"},
                {(ItemType.Jelly, Language.FR), "Gelée"},
                {(ItemType.Shell, Language.FR), "Coquille"},
                {(ItemType.Prism, Language.FR), "Prisme"},
                {(ItemType.LivingObjects, Language.FR), "Objet vivant"},
                {(ItemType.MagicWeapon, Language.FR), "Arme magique"},
                {(ItemType.FragmentOfShushuSoul, Language.FR), "Fragment d'âme de Shushu"},
                {(ItemType.PetPotion, Language.FR), "Potion de familier"},
                {(ItemType.CommonCard, Language.FR), "Carte commune"},
                {(ItemType.RareCard, Language.FR), "Carte rare"},
                {(ItemType.EpicCard, Language.FR), "Carte épique"},
                {(ItemType.UltimateCard, Language.FR), "Carte ultime"},
                {(ItemType.PackOfCards, Language.FR), "Paquet de cartes"},
                {(ItemType.DungeonKeeperSoulStone, Language.FR), "Pierre d'âme de gardien de donjon"},
                {(ItemType.ArchmonsterSoulStone, Language.FR), "Pierre d'âme d'Archi-monstre"},
                {(ItemType.Tonics, Language.FR), "Toniques"},
                {(ItemType.Empty, Language.FR), "[Réservé]"},
                {(ItemType.DofusFragment, Language.FR), "Fragment de Dofus"},
        
                // English Localization
                {(ItemType.Amulet, Language.EN), "Amulet"},
                {(ItemType.Bow, Language.EN), "Bow"},
                {(ItemType.Wand, Language.EN), "Wand"},
                {(ItemType.Staff, Language.EN), "Staff"},
                {(ItemType.Dagger, Language.EN), "Dagger"},
                {(ItemType.Sword, Language.EN), "Sword"},
                {(ItemType.Hammer, Language.EN), "Hammer"},
                {(ItemType.Shovel, Language.EN), "Shovel"},
                {(ItemType.Ring, Language.EN), "Ring"},
                {(ItemType.Belt, Language.EN), "Belt"},
                {(ItemType.Boots, Language.EN), "Boots"},
                {(ItemType.Potion, Language.EN), "Potion"},
                {(ItemType.ExperienceScroll, Language.EN), "Experience Scroll"},
                {(ItemType.GiftItem, Language.EN), "Gift Item"},
                {(ItemType.Resource, Language.EN), "Resource"},
                {(ItemType.Hat, Language.EN), "Hat"},
                {(ItemType.Cloak, Language.EN), "Cloak"},
                {(ItemType.Pet, Language.EN), "Pet"},
                {(ItemType.Axe, Language.EN), "Axe"},
                {(ItemType.Tool, Language.EN), "Tool"},
                {(ItemType.Pickaxe, Language.EN), "Pickaxe"},
                {(ItemType.Scythe, Language.EN), "Scythe"},
                {(ItemType.Dofus, Language.EN), "Dofus"},
                {(ItemType.QuestItem, Language.EN), "Quest Item"},
                {(ItemType.Document, Language.EN), "Document"},
                {(ItemType.SmithmagicPotion, Language.EN), "Smithmagic Potion"},
                {(ItemType.MutationItem, Language.EN), "Mutation Item"},
                {(ItemType.BoostFood, Language.EN), "Boost Food"},
                {(ItemType.Blessing, Language.EN), "Blessing"},
                {(ItemType.Curse, Language.EN), "Curse"},
                {(ItemType.RoleplayBuff, Language.EN), "Roleplay Buff"},
                {(ItemType.FollowingCharacter, Language.EN), "Following Character"},
                {(ItemType.Bread, Language.EN), "Bread"},
                {(ItemType.Cereal, Language.EN), "Cereal"},
                {(ItemType.Flower, Language.EN), "Flower"},
                {(ItemType.Plant, Language.EN), "Plant"},
                {(ItemType.Beer, Language.EN), "Beer"},
                {(ItemType.Wood, Language.EN), "Wood"},
                {(ItemType.Ore, Language.EN), "Ore"},
                {(ItemType.Alloy, Language.EN), "Alloy"},
                {(ItemType.Fish, Language.EN), "Fish"},
                {(ItemType.Candy, Language.EN), "Candy"},
                {(ItemType.ForgetfulnessPotion, Language.EN), "Forgetfulness Potion"},
                {(ItemType.UnlearningPotionForProfession, Language.EN), "Unlearning Potion for Profession"},
                {(ItemType.SkillLossPotion, Language.EN), "Skill Loss Potion"},
                {(ItemType.Fruit, Language.EN), "Fruit"},
                {(ItemType.Bone, Language.EN), "Bone"},
                {(ItemType.Powder, Language.EN), "Powder"},
                {(ItemType.EdibleFish, Language.EN), "Edible Fish"},
                {(ItemType.PreciousStone, Language.EN), "Precious Stone"},
                {(ItemType.Stone, Language.EN), "Stone"},
                {(ItemType.Flour, Language.EN), "Flour"},
                {(ItemType.Feather, Language.EN), "Feather"},
                {(ItemType.Hair, Language.EN), "Hair"},
                {(ItemType.Fabric, Language.EN), "Fabric"},
                {(ItemType.Leather, Language.EN), "Leather"},
                {(ItemType.Wool, Language.EN), "Wool"},
                {(ItemType.Seed, Language.EN), "Seed"},
                {(ItemType.Skin, Language.EN), "Skin"},
                {(ItemType.Oil, Language.EN), "Oil"},
                {(ItemType.StuffedAnimal, Language.EN), "Stuffed Animal"},
                {(ItemType.GuttedFish, Language.EN), "Gutted Fish"},
                {(ItemType.Meat, Language.EN), "Meat"},
                {(ItemType.PreservedMeat, Language.EN), "Preserved Meat"},
                {(ItemType.Tail, Language.EN), "Tail"},
                {(ItemType.Metaria, Language.EN), "Metaria"},
                {(ItemType.Vegetable, Language.EN), "Vegetable"},
                {(ItemType.EdibleMeat, Language.EN), "Edible Meat"},
                {(ItemType.Dyeing, Language.EN), "Dyeing"},
                {(ItemType.AlchemyEquipment, Language.EN), "Alchemy Equipment"},
                {(ItemType.PetEgg, Language.EN), "Pet Egg"},
                {(ItemType.Skill, Language.EN), "Skill"},
                {(ItemType.Fairywork, Language.EN), "Fairywork"},
                {(ItemType.SpellScroll, Language.EN), "Spell Scroll"},
                {(ItemType.CharacteristicScroll, Language.EN), "Characteristic Scroll"},
                {(ItemType.BowKennelCertificate, Language.EN), "Bow Kennel Certificate"},
                {(ItemType.SmithmagicRune, Language.EN), "Smithmagic Rune"},
                {(ItemType.Drink, Language.EN), "Drink"},
                {(ItemType.MissionItem, Language.EN), "Mission Item"},
                {(ItemType.Backpack, Language.EN), "Backpack"},
                {(ItemType.Shield, Language.EN), "Shield"},
                {(ItemType.SoulStone, Language.EN), "Soul Stone"},
                {(ItemType.Keys, Language.EN), "Keys"},
                {(ItemType.FullSoulStone, Language.EN), "Full Soul Stone"},
                {(ItemType.ForgetfulnessPotionForCollectors, Language.EN), "Forgetfulness Potion for Collectors"},
                {(ItemType.SeekerScroll, Language.EN), "Seeker Scroll"},
                {(ItemType.MagicStone, Language.EN), "Magic Stone"},
                {(ItemType.Gifts, Language.EN), "Gifts"},
                {(ItemType.PetGhost, Language.EN), "Pet Ghost"},
                {(ItemType.Dragoturkey, Language.EN), "Dragoturkey"},
                {(ItemType.Gobball, Language.EN), "Gobball"},
                {(ItemType.BreedingItem, Language.EN), "Breeding Item"},
                {(ItemType.UsableItem, Language.EN), "Usable Item"},
                {(ItemType.Plank, Language.EN), "Plank"},
                {(ItemType.Bark, Language.EN), "Bark"},
                {(ItemType.MountCertificate, Language.EN), "Mount Certificate"},
                {(ItemType.Root, Language.EN), "Root"},
                {(ItemType.CapturingNet, Language.EN), "Capturing Net"},
                {(ItemType.BagOfResources, Language.EN), "Bag of Resources"},
                {(ItemType.Crossbow, Language.EN), "Crossbow"},
                {(ItemType.Leg, Language.EN), "Leg"},
                {(ItemType.Wing, Language.EN), "Wing"},
                {(ItemType.Egg, Language.EN), "Egg"},
                {(ItemType.Ear, Language.EN), "Ear"},
                {(ItemType.Carapace, Language.EN), "Carapace"},
                {(ItemType.Bud, Language.EN), "Bud"},
                {(ItemType.Eye, Language.EN), "Eye"},
                {(ItemType.Jelly, Language.EN), "Jelly"},
                {(ItemType.Shell, Language.EN), "Shell"},
                {(ItemType.Prism, Language.EN), "Prism"},
                {(ItemType.LivingObjects, Language.EN), "Living Objects"},
                {(ItemType.MagicWeapon, Language.EN), "Magic Weapon"},
                {(ItemType.FragmentOfShushuSoul, Language.EN), "Fragment of Shushu Soul"},
                {(ItemType.PetPotion, Language.EN), "Pet Potion"},
                {(ItemType.CommonCard, Language.EN), "Common Card"},
                {(ItemType.RareCard, Language.EN), "Rare Card"},
                {(ItemType.EpicCard, Language.EN), "Epic Card"},
                {(ItemType.UltimateCard, Language.EN), "Ultimate Card"},
                {(ItemType.PackOfCards, Language.EN), "Pack of Cards"},
                {(ItemType.DungeonKeeperSoulStone, Language.EN), "Dungeon Keeper Soul Stone"},
                {(ItemType.ArchmonsterSoulStone, Language.EN), "Archmonster Soul Stone"},
                {(ItemType.Tonics, Language.EN), "Tonics"},
                {(ItemType.Empty, Language.EN), "[Reserved]"},
                {(ItemType.DofusFragment, Language.EN), "Dofus Fragment"},
        
                // Spanish Localization
                {(ItemType.Amulet, Language.ES), "Amuleto"},
                {(ItemType.Bow, Language.ES), "Arco"},
                {(ItemType.Wand, Language.ES), "Varita"},
                {(ItemType.Staff, Language.ES), "Bastón"},
                {(ItemType.Dagger, Language.ES), "Daga"},
                {(ItemType.Sword, Language.ES), "Espada"},
                {(ItemType.Hammer, Language.ES), "Martillo"},
                {(ItemType.Shovel, Language.ES), "Pala"},
                {(ItemType.Ring, Language.ES), "Anillo"},
                {(ItemType.Belt, Language.ES), "Cinturón"},
                {(ItemType.Boots, Language.ES), "Bota"},
                {(ItemType.Potion, Language.ES), "Pócima"},
                {(ItemType.ExperienceScroll, Language.ES), "Pergamino de experiencia"},
                {(ItemType.GiftItem, Language.ES), "Objeto de dones"},
                {(ItemType.Resource, Language.ES), "Recurso"},
                {(ItemType.Hat, Language.ES), "Sombrero"},
                {(ItemType.Cloak, Language.ES), "Capa"},
                {(ItemType.Pet, Language.ES), "Mascota"},
                {(ItemType.Axe, Language.ES), "Hacha"},
                {(ItemType.Tool, Language.ES), "Herramienta"},
                {(ItemType.Pickaxe, Language.ES), "Pico"},
                {(ItemType.Scythe, Language.ES), "Guadaña"},
                {(ItemType.Dofus, Language.ES), "Dofus"},
                {(ItemType.QuestItem, Language.ES), "Objeto de búsqueda"},
                {(ItemType.Document, Language.ES), "Documento"},
                {(ItemType.SmithmagicPotion, Language.ES), "Pócima de forjamagia"},
                {(ItemType.MutationItem, Language.ES), "Objeto de mutación"},
                {(ItemType.BoostFood, Language.ES), "Alimento boost"},
                {(ItemType.Blessing, Language.ES), "Bendición"},
                {(ItemType.Curse, Language.ES), "Maldición"},
                {(ItemType.RoleplayBuff, Language.ES), "Roleplay buffs"},
                {(ItemType.FollowingCharacter, Language.ES), "Personaje seguidor"},
                {(ItemType.Bread, Language.ES), "Pan"},
                {(ItemType.Cereal, Language.ES), "Cereal"},
                {(ItemType.Flower, Language.ES), "Flor"},
                {(ItemType.Plant, Language.ES), "Planta"},
                {(ItemType.Beer, Language.ES), "Cerveza"},
                {(ItemType.Wood, Language.ES), "Madera"},
                {(ItemType.Ore, Language.ES), "Mineral"},
                {(ItemType.Alloy, Language.ES), "Aleación"},
                {(ItemType.Fish, Language.ES), "Pez"},
                {(ItemType.Candy, Language.ES), "Golosina"},
                {(ItemType.ForgetfulnessPotion, Language.ES), "Pócima de olvido de hechizo"},
                {(ItemType.UnlearningPotionForProfession, Language.ES), "Pócima de olvido de oficio"},
                {(ItemType.SkillLossPotion, Language.ES), "Pócima de olvido de dominio"},
                {(ItemType.Fruit, Language.ES), "Fruta"},
                {(ItemType.Bone, Language.ES), "Hueso"},
                {(ItemType.Powder, Language.ES), "Polvo"},
                {(ItemType.EdibleFish, Language.ES), "Pescado comestible"},
                {(ItemType.PreciousStone, Language.ES), "Piedra preciosa"},
                {(ItemType.Stone, Language.ES), "Piedra bruta"},
                {(ItemType.Flour, Language.ES), "Harina"},
                {(ItemType.Feather, Language.ES), "Pluma"},
                {(ItemType.Hair, Language.ES), "Pelo"},
                {(ItemType.Fabric, Language.ES), "Tejido"},
                {(ItemType.Leather, Language.ES), "Cuero"},
                {(ItemType.Wool, Language.ES), "Lana"},
                {(ItemType.Seed, Language.ES), "Semilla"},
                {(ItemType.Skin, Language.ES), "Piel"},
                {(ItemType.Oil, Language.ES), "Aceite"},
                {(ItemType.StuffedAnimal, Language.ES), "Peluche"},
                {(ItemType.GuttedFish, Language.ES), "Pescado vaciado"},
                {(ItemType.Meat, Language.ES), "Carne"},
                {(ItemType.PreservedMeat, Language.ES), "Carne conservada"},
                {(ItemType.Tail, Language.ES), "Cola"},
                {(ItemType.Metaria, Language.ES), "Metaria"},
                {(ItemType.Vegetable, Language.ES), "Legumbre"},
                {(ItemType.EdibleMeat, Language.ES), "Carne comestible"},
                {(ItemType.Dyeing, Language.ES), "Tinte"},
                {(ItemType.AlchemyEquipment, Language.ES), "Material de alquimia"},
                {(ItemType.PetEgg, Language.ES), "Huevo de mascota"},
                {(ItemType.Skill, Language.ES), "Dominio"},
                {(ItemType.Fairywork, Language.ES), "Hada artificial"},
                {(ItemType.SpellScroll, Language.ES), "Pergamino de hechizo"},
                {(ItemType.CharacteristicScroll, Language.ES), "Pergamino de característica"},
                {(ItemType.BowKennelCertificate, Language.ES), "Certificado de admisión en la petrera"},
                {(ItemType.SmithmagicRune, Language.ES), "Runa de forjamagia"},
                {(ItemType.Drink, Language.ES), "Bebida"},
                {(ItemType.MissionItem, Language.ES), "Objeto de misión"},
                {(ItemType.Backpack, Language.ES), "Mochila"},
                {(ItemType.Shield, Language.ES), "Escudo"},
                {(ItemType.SoulStone, Language.ES), "Piedra de alma"},
                {(ItemType.Keys, Language.ES), "Llaves"},
                {(ItemType.FullSoulStone, Language.ES), "Piedra de alma llena"},
                {(ItemType.ForgetfulnessPotionForCollectors, Language.ES), "Pócima de olvido de recaudador"},
                {(ItemType.SeekerScroll, Language.ES), "Pergamino de búsqueda"},
                {(ItemType.MagicStone, Language.ES), "Piedra mágica"},
                {(ItemType.Gifts, Language.ES), "Regalos"},
                {(ItemType.PetGhost, Language.ES), "Fantasma de mascota"},
                {(ItemType.Dragoturkey, Language.ES), "Dragopavo"},
                {(ItemType.Gobball, Language.ES), "Jalató"},
                {(ItemType.BreedingItem, Language.ES), "Objeto de cría"},
                {(ItemType.UsableItem, Language.ES), "Objeto utilizable"},
                {(ItemType.Plank, Language.ES), "Tabla"},
                {(ItemType.Bark, Language.ES), "Corteza"},
                {(ItemType.MountCertificate, Language.ES), "Certificado de montura"},
                {(ItemType.Root, Language.ES), "Raíz"},
                {(ItemType.CapturingNet, Language.ES), "Red de captura"},
                {(ItemType.BagOfResources, Language.ES), "Sacos de recursos"},
                {(ItemType.Crossbow, Language.ES), "Ballesta"},
                {(ItemType.Leg, Language.ES), "Pata"},
                {(ItemType.Wing, Language.ES), "Ala"},
                {(ItemType.Egg, Language.ES), "Huevo"},
                {(ItemType.Ear, Language.ES), "Oreja"},
                {(ItemType.Carapace, Language.ES), "Caparazón"},
                {(ItemType.Bud, Language.ES), "Brote"},
                {(ItemType.Eye, Language.ES), "Ojo"},
                {(ItemType.Jelly, Language.ES), "Gelatina"},
                {(ItemType.Shell, Language.ES), "Cáscara"},
                {(ItemType.Prism, Language.ES), "Prisma"},
                {(ItemType.LivingObjects, Language.ES), "Objeto viviente"},
                {(ItemType.MagicWeapon, Language.ES), "Arma mágica"},
                {(ItemType.FragmentOfShushuSoul, Language.ES), "Fragmento de alma de fab'huritu"},
                {(ItemType.PetPotion, Language.ES), "Poción de mascota"},
                {(ItemType.CommonCard, Language.ES), "Carta común"},
                {(ItemType.RareCard, Language.ES), "Carta rara"},
                {(ItemType.EpicCard, Language.ES), "Carta épica"},
                {(ItemType.UltimateCard, Language.ES), "Carta definitiva"},
                {(ItemType.PackOfCards, Language.ES), "Sobre de cartas"},
                {(ItemType.DungeonKeeperSoulStone, Language.ES), "Piedra de alma de guardián de mazmorra"},
                {(ItemType.ArchmonsterSoulStone, Language.ES), "Piedra de alma de archimonstruo"},
                {(ItemType.Tonics, Language.ES), "Tónicos"},
                {(ItemType.Empty, Language.ES), "[Reservado]"},
                {(ItemType.DofusFragment, Language.ES), "Fragmento de Dofus"},
        };
        
        if (EcosystemNames == null || EcosystemNames.Count == 0)
            EcosystemNames = new ()
            {
                // FR names
                {(Ecosystem.VariousCreatures, Language.FR), "Créatures diverses"},
                {(Ecosystem.SwampCreatures, Language.FR), "Créatures des marécages"},
                {(Ecosystem.ForestCreatures, Language.FR), "Créatures de la forêt"},
                {(Ecosystem.PlainCreatures, Language.FR), "Créatures des plaines"},
                {(Ecosystem.FieldCreatures, Language.FR), "Créatures des champs"},
                {(Ecosystem.MoorCreatures, Language.FR), "Créatures des landes"},
                {(Ecosystem.MoonIslandCreatures, Language.FR), "Créatures de l'île de Moon"},
                {(Ecosystem.WabbitIslandCreatures, Language.FR), "Créatures de l'île des Wabbits"},
                {(Ecosystem.PandalaCreatures, Language.FR), "Créatures de Pandala"},
                {(Ecosystem.HumanoidCreatures, Language.FR), "Créatures humanoïdes"},
                {(Ecosystem.DarkCreatures, Language.FR), "Créatures de la nuit"},
                {(Ecosystem.ResourcesProtectors, Language.FR), "Protecteurs des ressources"},
                {(Ecosystem.CityCreatures, Language.FR), "Créatures des villes"},
                {(Ecosystem.BreederVillageCreatures, Language.FR), "Créatures du village des éleveurs"},
                {(Ecosystem.BeachCreatures, Language.FR), "Créatures des plages"},
                {(Ecosystem.MinotororIslandCreatures, Language.FR), "Créatures de l'île du Minotoror"},
                {(Ecosystem.MountainCreatures, Language.FR), "Créatures de la montagne"},
                {(Ecosystem.BeginnerAreaCreatures, Language.FR), "Créatures de la zone des débutants"},
                {(Ecosystem.OtomaiIslandCreatures, Language.FR), "Créatures de l'île d'Otomaï"},
                {(Ecosystem.Archmonsters, Language.FR), "Créatures Archi-monstres"},
                
                // English names
                {(Ecosystem.VariousCreatures, Language.EN), "Various creatures"},
                {(Ecosystem.SwampCreatures, Language.EN), "Swamp creatures"},
                {(Ecosystem.ForestCreatures, Language.EN), "Forest creatures"},
                {(Ecosystem.PlainCreatures, Language.EN), "Plain creatures"},
                {(Ecosystem.FieldCreatures, Language.EN), "Field creatures"},
                {(Ecosystem.MoorCreatures, Language.EN), "Moor creatures"},
                {(Ecosystem.MoonIslandCreatures, Language.EN), "Moon Island creatures"},
                {(Ecosystem.WabbitIslandCreatures, Language.EN), "Wabbit Island creatures"},
                {(Ecosystem.PandalaCreatures, Language.EN), "Pandala creatures"},
                {(Ecosystem.HumanoidCreatures, Language.EN), "Humanoid creatures"},
                {(Ecosystem.DarkCreatures, Language.EN), "Dark creatures"},
                {(Ecosystem.ResourcesProtectors, Language.EN), "Resource Protectors"},
                {(Ecosystem.CityCreatures, Language.EN), "City creatures"},
                {(Ecosystem.BreederVillageCreatures, Language.EN), "Breeder Village creatures"},
                {(Ecosystem.BeachCreatures, Language.EN), "Beach creatures"},
                {(Ecosystem.MinotororIslandCreatures, Language.EN), "Minotoror Island creatures"},
                {(Ecosystem.MountainCreatures, Language.EN), "Mountain creatures"},
                {(Ecosystem.BeginnerAreaCreatures, Language.EN), "Beginner Area creatures"},
                {(Ecosystem.OtomaiIslandCreatures, Language.EN), "Otomai Island creatures"},
                {(Ecosystem.Archmonsters, Language.EN), "Archmonsters"},
                
                // Spanish names
                {(Ecosystem.VariousCreatures, Language.ES), "Criaturas diversas"},
                {(Ecosystem.SwampCreatures, Language.ES), "Criaturas de los pantanos"},
                {(Ecosystem.ForestCreatures, Language.ES), "Criaturas del bosque"},
                {(Ecosystem.PlainCreatures, Language.ES), "Criaturas de las llanuras"},
                {(Ecosystem.FieldCreatures, Language.ES), "Criaturas de los campos"},
                {(Ecosystem.MoorCreatures, Language.ES), "Criaturas de las landas"},
                {(Ecosystem.MoonIslandCreatures, Language.ES), "Criaturas de la Isla de Moon"},
                {(Ecosystem.WabbitIslandCreatures, Language.ES), "Criaturas de la Isla de los Wabbits"},
                {(Ecosystem.PandalaCreatures, Language.ES), "Criaturas de Pandala"},
                {(Ecosystem.HumanoidCreatures, Language.ES), "Criaturas humanoides"},
                {(Ecosystem.DarkCreatures, Language.ES), "Criaturas de la noche"},
                {(Ecosystem.ResourcesProtectors, Language.ES), "Protectores de los recursos"},
                {(Ecosystem.CityCreatures, Language.ES), "Criaturas de las ciudades"},
                {(Ecosystem.BreederVillageCreatures, Language.ES), "Criaturas del pueblo de los ganaderos"},
                {(Ecosystem.BeachCreatures, Language.ES), "Criaturas de las playas"},
                {(Ecosystem.MinotororIslandCreatures, Language.ES), "Criaturas de la isla de Minotauroro"},
                {(Ecosystem.MountainCreatures, Language.ES), "Criaturas de la montaña"},
                {(Ecosystem.BeginnerAreaCreatures, Language.ES), "Criaturas de la zona de los novatos"},
                {(Ecosystem.OtomaiIslandCreatures, Language.ES), "Criaturas de la isla de Otomai"},
                {(Ecosystem.Archmonsters, Language.ES), "Criaturas Archi-monstruo"}
            };
        
        if (BreedNames == null || BreedNames.Count == 0)
            BreedNames = new ()
            {
                // FR names
                {(Breed.Arachnee, Language.FR), "Arakne"},
                {(Breed.Archmonsters, Language.FR), "Les Archi-monstres"},
                {(Breed.Bandits, Language.FR), "Bandits"},
                {(Breed.BeachMonsters, Language.FR), "Monstres des plages"},
                {(Breed.Blop, Language.FR), "Mulou"},
                {(Breed.Boowolf, Language.FR), "Boowolf"},
                {(Breed.Boss, Language.FR), "Boss"},
                {(Breed.BottomlessPeatBogMonsters, Language.FR), "Monstres de la Tourbière sans fond"},
                {(Breed.Bworks, Language.FR), "Bworks"},
                {(Breed.CaniaPlainMonsters, Language.FR), "Monstres des Plaines de Cania"},
                {(Breed.CaveMonsters, Language.FR), "Monstres des cavernes"},
                {(Breed.CerealProtectors, Language.FR), "Protecteurs des Céréales"},
                {(Breed.Chafers, Language.FR), "Chafers"},
                {(Breed.ClassSummonings, Language.FR), "Invocations de classe"},
                {(Breed.CoralBeachMonsters, Language.FR), "Monstres de la plage de corail"},
                {(Breed.Cracklers, Language.FR), "Craqueleurs"},
                {(Breed.Crocodyls, Language.FR), "Crocodailles"},
                {(Breed.Crows, Language.FR), "Corbacs"},
                {(Breed.DarkJungleMonsters, Language.FR), "Monstres de la Jungle Sombre"},
                {(Breed.DoppleTemple, Language.FR), "Dopeuls Temple"},
                {(Breed.DoppleVillageMonsters, Language.FR), "Monstres du Village des Dopeuls"},
                {(Breed.Dragoturkeys, Language.FR), "Dragodinde"},
                {(Breed.Dreggons, Language.FR), "Dragoeufs"},
                {(Breed.FieldMonsters, Language.FR), "Plantes des champs"},
                {(Breed.Firefoux, Language.FR), "Firefoux"},
                {(Breed.FishProtectors, Language.FR), "Protecteurs des Poissons"},
                {(Breed.FoggyCanopyMonsters, Language.FR), "Monstres de la Canopée Embrumée"},
                {(Breed.ForestAnimals, Language.FR), "Animaux de la forêt"},
                {(Breed.Ghosts, Language.FR), "Fantômes"},
                {(Breed.Gobbals, Language.FR), "Bouftous"},
                {(Breed.Goblins, Language.FR), "Gobelins"},
                {(Breed.GrassyPlainMonsters, Language.FR), "Monstres des Plaines herbeuses"},
                {(Breed.Guards, Language.FR), "Gardes"},
                {(Breed.Imps, Language.FR), "Brigandins"},
                {(Breed.Jellies, Language.FR), "Gelées"},
                {(Breed.Kitsous, Language.FR), "Kitsous"},
                {(Breed.Koalaks, Language.FR), "Koalaks"},
                {(Breed.KwakVillageGuardians, Language.FR), "Gardiens des villages de Kwaks"},
                {(Breed.Kwaks, Language.FR), "Kwaks"},
                {(Breed.KwismasMonsters, Language.FR), "Monstres de Nowel"},
                {(Breed.Larvae, Language.FR), "Larves"},
                {(Breed.Minos, Language.FR), "Minos"},
                {(Breed.MonstersFromTheBeginningArea, Language.FR), "Monstres de la zone des débutants"},
                {(Breed.MoonIslandKannibals, Language.FR), "Kannibouls de l'île de Moon"},
                {(Breed.MoonMonsters, Language.FR), "Monstres de Moon"},
                {(Breed.MoonPirates, Language.FR), "Pirates de Moon"},
                {(Breed.MoonPlants, Language.FR), "Plantes de Moon"},
                {(Breed.MoonTurtles, Language.FR), "Tortues de Moon"},
                {(Breed.MoorMonsters, Language.FR), "Monstres des landes"},
                {(Breed.Moskitos, Language.FR), "Moskitos"},
                {(Breed.Mushrooms, Language.FR), "Champignons"},
                {(Breed.NightMonsters, Language.FR), "Monstres de la nuit"},
                {(Breed.NotListed, Language.FR), "Non classé"},
                {(Breed.Npc, Language.FR), "Pnjs"},
                {(Breed.OreProtectors, Language.FR), "Protecteurs des Minerais"},
                {(Breed.OtomaiArkMonsters, Language.FR), "Monstres de l'Arche d'Otomaï"},
                {(Breed.PandalaGhost, Language.FR), "Fantôme de Pandala"},
                {(Breed.PandalaMonsters, Language.FR), "Monstres de Pandala"},
                {(Breed.PandalaPlants, Language.FR), "Plantes de Pandala"},
                {(Breed.PandalaVillageMonsters, Language.FR), "Monstres du village de Pandala"},
                {(Breed.Pandawas, Language.FR), "Pandawas"},
                {(Breed.PetGhosts, Language.FR), "Familiers Fantômes"},
                {(Breed.Pigs, Language.FR), "Cochons"},
                {(Breed.Piwis, Language.FR), "Pious"},
                {(Breed.PlantProtectors, Language.FR), "Protecteurs des Plantes"},
                {(Breed.QuestMonsters, Language.FR), "Monstres de quête"},
                {(Breed.Scaraleaf, Language.FR), "Scarafeuille"},
                {(Breed.SewerMonsters, Language.FR), "Monstre des égouts"},
                {(Breed.SwampMonsters, Language.FR), "Monstres des marécages"},
                {(Breed.TerritoryQuestMonsters, Language.FR), "Monstres des conquêtes de territoires"},
                {(Breed.Tofus, Language.FR), "Tofus"},
                {(Breed.TreeKeeholoMonsters, Language.FR), "Monstres de l'Arbre Hakam"},
                {(Breed.TreeProtectors, Language.FR), "Protecteurs des Arbres"},
                {(Breed.Treechnidian, Language.FR), "Treechnidian"},
                {(Breed.TutorialMonsters, Language.FR), "Monstres Tutorial"},
                {(Breed.Wabbits, Language.FR), "Wabbits"},
                {(Breed.Wanted, Language.FR), "Avis de recherche"},
                
                // English names
                {(Breed.Arachnee, Language.EN), "Arachnee"},
                {(Breed.Archmonsters, Language.EN), "Archmonsters"},
                {(Breed.Bandits, Language.EN), "Bandits"},
                {(Breed.BeachMonsters, Language.EN), "Beach Monsters"},
                {(Breed.Blop, Language.EN), "Blop"},
                {(Breed.Boowolf, Language.EN), "Boowolf"},
                {(Breed.Boss, Language.EN), "Boss"},
                {(Breed.BottomlessPeatBogMonsters, Language.EN), "Bottomless Peat Bog Monsters"},
                {(Breed.Bworks, Language.EN), "Bworks"},
                {(Breed.CaniaPlainMonsters, Language.EN), "Cania Plain Monsters"},
                {(Breed.CaveMonsters, Language.EN), "Cave Monsters"},
                {(Breed.CerealProtectors, Language.EN), "Cereal Protectors"},
                {(Breed.Chafers, Language.EN), "Chafers"},
                {(Breed.ClassSummonings, Language.EN), "Class Summonings"},
                {(Breed.CoralBeachMonsters, Language.EN), "Coral Beach Monsters"},
                {(Breed.Cracklers, Language.EN), "Cracklers"},
                {(Breed.Crocodyls, Language.EN), "Crocodyls"},
                {(Breed.Crows, Language.EN), "Crows"},
                {(Breed.DarkJungleMonsters, Language.EN), "Dark Jungle Monsters"},
                {(Breed.DoppleTemple, Language.EN), "Dopple Temple"},
                {(Breed.DoppleVillageMonsters, Language.EN), "Dopple Village Monsters"},
                {(Breed.Dragoturkeys, Language.EN), "Dragoturkey"},
                {(Breed.Dreggons, Language.EN), "Dreggons"},
                {(Breed.FieldMonsters, Language.EN), "Field Monsters"},
                {(Breed.Firefoux, Language.EN), "Firefoux"},
                {(Breed.FishProtectors, Language.EN), "Fish Protectors"},
                {(Breed.FoggyCanopyMonsters, Language.EN), "Foggy Canopy Monsters"},
                {(Breed.ForestAnimals, Language.EN), "Forest animals"},
                {(Breed.Ghosts, Language.EN), "Ghosts"},
                {(Breed.Gobbals, Language.EN), "Gobballs"},
                {(Breed.Goblins, Language.EN), "Goblins"},
                {(Breed.GrassyPlainMonsters, Language.EN), "Grassy Plain Monsters"},
                {(Breed.Guards, Language.EN), "Guards"},
                {(Breed.Imps, Language.EN), "Imps"},
                {(Breed.Jellies, Language.EN), "Jellies"},
                {(Breed.Kitsous, Language.EN), "Kitsous"},
                {(Breed.Koalaks, Language.EN), "Koalaks"},
                {(Breed.KwakVillageGuardians, Language.EN), "Kwak Villages Guardians"},
                {(Breed.Kwaks, Language.EN), "Kwaks"},
                {(Breed.KwismasMonsters, Language.EN), "Kwismas Monsters"},
                {(Breed.Larvae, Language.EN), "Larvae"},
                {(Breed.Minos, Language.EN), "Minos"},
                {(Breed.MonstersFromTheBeginningArea, Language.EN), "Monsters from the Beginner Area"},
                {(Breed.MoonIslandKannibals, Language.EN), "Moon Island Kanniballs"},
                {(Breed.MoonMonsters, Language.EN), "Moon Monsters"},
                {(Breed.MoonPirates, Language.EN), "Moon Pirates"},
                {(Breed.MoonPlants, Language.EN), "Moon Plants"},
                {(Breed.MoonTurtles, Language.EN), "Moon Turtles"},
                {(Breed.MoorMonsters, Language.EN), "Moor Monsters"},
                {(Breed.Moskitos, Language.EN), "Moskitos"},
                {(Breed.Mushrooms, Language.EN), "Mushrooms"},
                {(Breed.NightMonsters, Language.EN), "Night Monsters"},
                {(Breed.NotListed, Language.EN), "Not Listed"},
                {(Breed.Npc, Language.EN), "NPCs"},
                {(Breed.OreProtectors, Language.EN), "Ore Protectors"},
                {(Breed.OtomaiArkMonsters, Language.EN), "Otomai's Ark Monsters"},
                {(Breed.PandalaGhost, Language.EN), "Pandala Ghost"},
                {(Breed.PandalaMonsters, Language.EN), "Pandala Monsters"},
                {(Breed.PandalaPlants, Language.EN), "Pandala Plants"},
                {(Breed.PandalaVillageMonsters, Language.EN), "Pandala Village Monsters"},
                {(Breed.Pandawas, Language.EN), "Pandawas"},
                {(Breed.PetGhosts, Language.EN), "Pet Ghosts"},
                {(Breed.Pigs, Language.EN), "Pigs"},
                {(Breed.Piwis, Language.EN), "Piwis"},
                {(Breed.PlantProtectors, Language.EN), "Plant Protectors"},
                {(Breed.QuestMonsters, Language.EN), "Quest Monsters"},
                {(Breed.Scaraleaf, Language.EN), "Scaraleaf"},
                {(Breed.SewerMonsters, Language.EN), "Sewers Monsters"},
                {(Breed.SwampMonsters, Language.EN), "Swamp Monsters"},
                {(Breed.TerritoryQuestMonsters, Language.EN), "Territory Quest Monsters"},
                {(Breed.Tofus, Language.EN), "Tofus"},
                {(Breed.TreeKeeholoMonsters, Language.EN), "Tree Keeholo Monsters"},
                {(Breed.TreeProtectors, Language.EN), "Tree Protectors"},
                {(Breed.Treechnidian, Language.EN), "Treechnidian"},
                {(Breed.TutorialMonsters, Language.EN), "Tutorial Monsters"},
                {(Breed.Wabbits, Language.EN), "Wabbits"},
                {(Breed.Wanted, Language.EN), "Wanted"},
                
                // Spanish names
                {(Breed.Arachnee, Language.ES), "Arakna"},
                {(Breed.Archmonsters, Language.ES), "Los Archi-monstruos"},
                {(Breed.Bandits, Language.ES), "Bandidos"},
                {(Breed.BeachMonsters, Language.ES), "Monstruos de las playas"},
                {(Breed.Blop, Language.ES), "Milubo"},
                {(Breed.Boowolf, Language.ES), "Boowolf"},
                {(Breed.Boss, Language.ES), "Jefe final"},
                {(Breed.BottomlessPeatBogMonsters, Language.ES), "Monstruos de la Turbera sin fondo"},
                {(Breed.Bworks, Language.ES), "Bworks"},
                {(Breed.CaniaPlainMonsters, Language.ES), "Monstruos de las Llanuras de Cania"},
                {(Breed.CaveMonsters, Language.ES), "Monstruos de las cuevas"},
                {(Breed.CerealProtectors, Language.ES), "Protectores de los cereales"},
                {(Breed.Chafers, Language.ES), "Chafers"},
                {(Breed.ClassSummonings, Language.ES), "Invocaciones de clase"},
                {(Breed.CoralBeachMonsters, Language.ES), "Monstruos de la playa de coral"},
                {(Breed.Cracklers, Language.ES), "Crujidores"},
                {(Breed.Crocodyls, Language.ES), "Cocodrails"},
                {(Breed.Crows, Language.ES), "Cuerboks"},
                {(Breed.DarkJungleMonsters, Language.ES), "Monstruos de la Oscura Selva"},
                {(Breed.DoppleTemple, Language.ES), "Dopeuls Templo"},
                {(Breed.DoppleVillageMonsters, Language.ES), "Monstruos del Pueblo de los Dopeuls"},
                {(Breed.Dragoturkeys, Language.ES), "Dragopavo"},
                {(Breed.Dreggons, Language.ES), "Dragohuevos"},
                {(Breed.FieldMonsters, Language.ES), "Plantas de los campos"},
                {(Breed.Firefoux, Language.ES), "Firefux"},
                {(Breed.FishProtectors, Language.ES), "Protectores de los Peces"},
                {(Breed.FoggyCanopyMonsters, Language.ES), "Monstruos de la Canopea de las Nieblas"},
                {(Breed.ForestAnimals, Language.ES), "Animales del bosque"},
                {(Breed.Ghosts, Language.ES), "Fantasmas"},
                {(Breed.Gobbals, Language.ES), "Blops"},
                {(Breed.Goblins, Language.ES), "Goblins"},
                {(Breed.GrassyPlainMonsters, Language.ES), "Monstruos de las Llanuras herbosas"},
                {(Breed.Guards, Language.ES), "Guardias"},
                {(Breed.Imps, Language.ES), "Salteadorillos"},
                {(Breed.Jellies, Language.ES), "Gelatinas"},
                {(Breed.Kitsous, Language.ES), "Kitsus"},
                {(Breed.Koalaks, Language.ES), "Koalaks"},
                {(Breed.KwakVillageGuardians, Language.ES), "Guardianes de los pueblos de Kwaks"},
                {(Breed.Kwaks, Language.ES), "Kwaks"},
                {(Breed.KwismasMonsters, Language.ES), "Monstruos de Nawidad"},
                {(Breed.Larvae, Language.ES), "Larvas"},
                {(Breed.Minos, Language.ES), "Minos"},
                {(Breed.MonstersFromTheBeginningArea, Language.ES), "Monstruos de la zona de novatos"},
                {(Breed.MoonIslandKannibals, Language.ES), "Kaníbolas de la Isla de Moon"},
                {(Breed.MoonMonsters, Language.ES), "Monstruos de Moon"},
                {(Breed.MoonPirates, Language.ES), "Piratas de Moon"},
                {(Breed.MoonPlants, Language.ES), "Plantas de Moon"},
                {(Breed.MoonTurtles, Language.ES), "Tortugas de Moon"},
                {(Breed.MoorMonsters, Language.ES), "Monstruos de las landas"},
                {(Breed.Moskitos, Language.ES), "Moskitos"},
                {(Breed.Mushrooms, Language.ES), "Setas"},
                {(Breed.NightMonsters, Language.ES), "Monstruos de la noche"},
                {(Breed.NotListed, Language.ES), "Sin clasificar"},
                {(Breed.Npc, Language.ES), "Pnjs"},
                {(Breed.OreProtectors, Language.ES), "Protectores de los Minerales"},
                {(Breed.OtomaiArkMonsters, Language.ES), "Monstruos del Arca de Otomai"},
                {(Breed.PandalaGhost, Language.ES), "Fantasma de Pandala"},
                {(Breed.PandalaMonsters, Language.ES), "Monstruos de Pandala"},
                {(Breed.PandalaPlants, Language.ES), "Plantas de Pandala"},
                {(Breed.PandalaVillageMonsters, Language.ES), "Monstruos del pueblo de Pandala"},
                {(Breed.Pandawas, Language.ES), "Pandawas"},
                {(Breed.PetGhosts, Language.ES), "Mascotas Fantasmas"},
                {(Breed.Pigs, Language.ES), "Cerdos"},
                {(Breed.Piwis, Language.ES), "Jalatós"},
                {(Breed.PlantProtectors, Language.ES), "Protectores de las Plantas"},
                {(Breed.QuestMonsters, Language.ES), "Monstruos de búsqueda"},
                {(Breed.Scaraleaf, Language.ES), "Escarahoja"},
                {(Breed.SewerMonsters, Language.ES), "Monstruo de las alcantarillas"},
                {(Breed.SwampMonsters, Language.ES), "Monstruos de los pantanos"},
                {(Breed.TerritoryQuestMonsters, Language.ES), "Monstruos de las conquistas de territorios"},
                {(Breed.Tofus, Language.ES), "Tofus"},
                {(Breed.TreeKeeholoMonsters, Language.ES), "Monstruos del Árbol Hakam"},
                {(Breed.TreeProtectors, Language.ES), "Protectores de los árboles"},
                {(Breed.Treechnidian, Language.ES), "Treechnidian"},
                {(Breed.TutorialMonsters, Language.ES), "Monstruos Tutorial"},
                {(Breed.Wabbits, Language.ES), "Wabbits"},
                {(Breed.Wanted, Language.ES), "Se busca"}
            };
        
        if (CardFamilyNames == null || CardFamilyNames.Count == 0)
            CardFamilyNames = new ()
            {
                // French localized Names
                {(CardFamily.Bandits, Language.FR), "Bandits"},
                {(CardFamily.Bworks, Language.FR), "Bworks"},
                {(CardFamily.Wabbits, Language.FR), "Wabbits"},
                {(CardFamily.Dreggons, Language.FR), "Dragoeufs"},
                {(CardFamily.Jellies, Language.FR), "Gelées"},
                {(CardFamily.NightMonsters, Language.FR), "Monstres de la nuit"},
                {(CardFamily.Gobballs, Language.FR), "Bouftous"},
                {(CardFamily.FieldVermin, Language.FR), "Vermines des champs"},
                {(CardFamily.Larvae, Language.FR), "Larves"},
                {(CardFamily.KwaksAndCracklers, Language.FR), "Kwaks et Craqueleurs"},
                {(CardFamily.Pigs, Language.FR), "Cochons"},
                {(CardFamily.Chafers, Language.FR), "Chafers"},
                {(CardFamily.Dopple, Language.FR), "Dopeuls"},
                {(CardFamily.MoonMonsters, Language.FR), "Monstres de la forêt de Moon"},
                {(CardFamily.Treechnidian, Language.FR), "Abraknydiens"},
                {(CardFamily.Blop, Language.FR), "Blops"},
                {(CardFamily.CaniaCreatures, Language.FR), "Créatures de Cania"},
                {(CardFamily.Sidimonsters, Language.FR), "Sidimonstres"},
                {(CardFamily.Rats, Language.FR), "Rats"},
                {(CardFamily.Wanted, Language.FR), "Avis de recherche"},
                {(CardFamily.Scaraleaf, Language.FR), "Scarafeuilles"},
                {(CardFamily.Arachnee, Language.FR), "Araknes"},
                {(CardFamily.CanidaeAndForestAnimals, Language.FR), "Canidés et animaux de la forêt"},
                {(CardFamily.Swampsters, Language.FR), "Gadouilleux"},
                {(CardFamily.Mushrooms, Language.FR), "Champignons"},
                {(CardFamily.Tofus, Language.FR), "Tofus"},
                {(CardFamily.Crows, Language.FR), "Corbacs"},
                {(CardFamily.Koalaks, Language.FR), "Koalaks"},
                {(CardFamily.MortalKoalaks, Language.FR), "Koalaks mortels"},
                {(CardFamily.Minos, Language.FR), "Minos"},
                {(CardFamily.BeachMonsters, Language.FR), "Monstres des plages"},
                {(CardFamily.Herboreals, Language.FR), "Herboricoles"},
                {(CardFamily.CoralatorColony, Language.FR), "Colonie du Magistral"},
                {(CardFamily.PeatBogMonsters, Language.FR), "Monstres des Tourbières"},
                {(CardFamily.DarkFlorifauna, Language.FR), "Florifaune obscure"},
                {(CardFamily.TreePeople, Language.FR), "Peuple de l'Arbre"},
                {(CardFamily.PiratesDeLarcheDOtomai, Language.FR), "Pirates de l'Arche d'Otomaï"},
                {(CardFamily.Zoths, Language.FR), "Zoths"},
                {(CardFamily.PandalaPlants, Language.FR), "Plantes de Pandala"},
                {(CardFamily.Kitsous, Language.FR), "Kitsous"},
                {(CardFamily.Pandissidents, Language.FR), "Pandissidans"},
                {(CardFamily.Firefoux, Language.FR), "Firefoux"},
                {(CardFamily.PandalaGhost, Language.FR), "Fantômes de Pandala"},
                {(CardFamily.FreaksOfNature, Language.FR), "Curiosités de la nature"},
                {(CardFamily.MinorDivinities, Language.FR), "Divinités mineures"},
                // English localized Names
                {(CardFamily.Bandits, Language.EN), "Bandits"},
                {(CardFamily.Bworks, Language.EN), "Bworks"},
                {(CardFamily.Wabbits, Language.EN), "Wabbits"},
                {(CardFamily.Dreggons, Language.EN), "Dreggons"},
                {(CardFamily.Jellies, Language.EN), "Jellies"},
                {(CardFamily.NightMonsters, Language.EN), "Night Monsters"},
                {(CardFamily.Gobballs, Language.EN), "Gobballs"},
                {(CardFamily.FieldVermin, Language.EN), "Field Vermin"},
                {(CardFamily.Larvae, Language.EN), "Larvae"},
                {(CardFamily.KwaksAndCracklers, Language.EN), "Kwaks and Cracklers"},
                {(CardFamily.Pigs, Language.EN), "Pigs"},
                {(CardFamily.Chafers, Language.EN), "Chafers"},
                {(CardFamily.Dopple, Language.EN), "Dopple"},
                {(CardFamily.MoonMonsters, Language.EN), "Moon Monsters"},
                {(CardFamily.Treechnidian, Language.EN), "Treechnidian"},
                {(CardFamily.Blop, Language.EN), "Blop"},
                {(CardFamily.CaniaCreatures, Language.EN), "Cania Creatures"},
                {(CardFamily.Sidimonsters, Language.EN), "Sidimonsters"},
                {(CardFamily.Rats, Language.EN), "Rats"},
                {(CardFamily.Wanted, Language.EN), "Wanted"},
                {(CardFamily.Scaraleaf, Language.EN), "Scaraleaf"},
                {(CardFamily.Arachnee, Language.EN), "Arachnee"},
                {(CardFamily.CanidaeAndForestAnimals, Language.EN), "Canidae and forest animals"},
                {(CardFamily.Swampsters, Language.EN), "Swampsters"},
                {(CardFamily.Mushrooms, Language.EN), "Mushrooms"},
                {(CardFamily.Tofus, Language.EN), "Tofus"},
                {(CardFamily.Crows, Language.EN), "Crows"},
                {(CardFamily.Koalaks, Language.EN), "Koalaks"},
                {(CardFamily.MortalKoalaks, Language.EN), "Mortal Koalaks"},
                {(CardFamily.Minos, Language.EN), "Minos"},
                {(CardFamily.BeachMonsters, Language.EN), "Beach Monsters"},
                {(CardFamily.Herboreals, Language.EN), "Herboreals"},
                {(CardFamily.CoralatorColony, Language.EN), "Coralator Colony"},
                {(CardFamily.PeatBogMonsters, Language.EN), "Peat Bog Monsters"},
                {(CardFamily.DarkFlorifauna, Language.EN), "Dark Florifauna"},
                {(CardFamily.TreePeople, Language.EN), "Tree People"},
                {(CardFamily.PiratesDeLarcheDOtomai, Language.EN), "Pirates de l'Arche d'Otomaï"},
                {(CardFamily.Zoths, Language.EN), "Zoths"},
                {(CardFamily.PandalaPlants, Language.EN), "Pandala Plants"},
                {(CardFamily.Kitsous, Language.EN), "Kitsous"},
                {(CardFamily.Pandissidents, Language.EN), "Pandissidents"},
                {(CardFamily.Firefoux, Language.EN), "Firefoux"},
                {(CardFamily.PandalaGhost, Language.EN), "Pandala Ghost"},
                {(CardFamily.FreaksOfNature, Language.EN), "Freaks of Nature"},
                {(CardFamily.MinorDivinities, Language.EN), "Minor Divinities"},
                // Spanish localized Names
                {(CardFamily.Bandits, Language.ES), "Bandidos"},
                {(CardFamily.Bworks, Language.ES), "Bworks"},
                {(CardFamily.Wabbits, Language.ES), "Wabbits"},
                {(CardFamily.Dreggons, Language.ES), "Dragohuevos"},
                {(CardFamily.Jellies, Language.ES), "Gelatinas"},
                {(CardFamily.NightMonsters, Language.ES), "Monstruos de la noche"},
                {(CardFamily.Gobballs, Language.ES), "Jalatós"},
                {(CardFamily.FieldVermin, Language.ES), "Alimañas de los campos"},
                {(CardFamily.Larvae, Language.ES), "Larvas"},
                {(CardFamily.KwaksAndCracklers, Language.ES), "Kwaks y Crujidores"},
                {(CardFamily.Pigs, Language.ES), "Cerdos"},
                {(CardFamily.Chafers, Language.ES), "Chafers"},
                {(CardFamily.Dopple, Language.ES), "Dopeuls"},
                {(CardFamily.MoonMonsters, Language.ES), "Monstruos de Moon"},
                {(CardFamily.Treechnidian, Language.ES), "Abraknídeo"},
                {(CardFamily.Blop, Language.ES), "Blops"},
                {(CardFamily.CaniaCreatures, Language.ES), "Criaturas de Cania"},
                {(CardFamily.Sidimonsters, Language.ES), "Sidimonstruos"},
                {(CardFamily.Rats, Language.ES), "Ratas"},
                {(CardFamily.Wanted, Language.ES), "Se busca"},
                {(CardFamily.Scaraleaf, Language.ES), "Escarahoja"},
                {(CardFamily.Arachnee, Language.ES), "Arakna"},
                {(CardFamily.CanidaeAndForestAnimals, Language.ES), "Cánidos y animales del bosque"},
                {(CardFamily.Swampsters, Language.ES), "Barronstruos"},
                {(CardFamily.Mushrooms, Language.ES), "Setas"},
                {(CardFamily.Tofus, Language.ES), "Tofus"},
                {(CardFamily.Crows, Language.ES), "Cuerboks"},
                {(CardFamily.Koalaks, Language.ES), "Koalaks"},
                {(CardFamily.MortalKoalaks, Language.ES), "Koalaks mortales"},
                {(CardFamily.Minos, Language.ES), "Minos"},
                {(CardFamily.BeachMonsters, Language.ES), "Monstruos de las playas"},
                {(CardFamily.Herboreals, Language.ES), "Hierborícolas"},
                {(CardFamily.CoralatorColony, Language.ES), "Colonia del Magistral"},
                {(CardFamily.PeatBogMonsters, Language.ES), "Monstruo de la turbera"},
                {(CardFamily.DarkFlorifauna, Language.ES), "Florifauna oscura"},
                {(CardFamily.TreePeople, Language.ES), "Pueblo del árbol"},
                {(CardFamily.PiratesDeLarcheDOtomai, Language.ES), "Piratas del arca de Otomai"},
                {(CardFamily.Zoths, Language.ES), "Zoths"},
                {(CardFamily.PandalaPlants, Language.ES), "Plantas de Pandala"},
                {(CardFamily.Kitsous, Language.ES), "Kitsus"},
                {(CardFamily.Pandissidents, Language.ES), "Pandisidentes"},
                {(CardFamily.Firefoux, Language.ES), "Firefux"},
                {(CardFamily.PandalaGhost, Language.ES), "Fantasma de Pandala"},
                {(CardFamily.FreaksOfNature, Language.ES), "Curiosidades de la naturaleza"},
                {(CardFamily.MinorDivinities, Language.ES), "Divinidades menores"}
            };
        
        if (PlayableClassNames == null || PlayableClassNames.Count == 0)
        {
            PlayableClassNames = new Dictionary<(PlayableClass, Language), string>()
            {
                {(PlayableClass.Feca, Language.FR), "Feca"},
                {(PlayableClass.Osamodas, Language.FR), "Osamodas"},
                {(PlayableClass.Enutrof, Language.FR), "Enutrof"},
                {(PlayableClass.Sram, Language.FR), "Sram"},
                {(PlayableClass.Xelor, Language.FR), "Xelor"},
                {(PlayableClass.Ecaflip, Language.FR), "Ecaflip"},
                {(PlayableClass.Eniripsa, Language.FR), "Eniripsa"},
                {(PlayableClass.Iop, Language.FR), "Iop"},
                {(PlayableClass.Cra, Language.FR), "Cra"},
                {(PlayableClass.Sadida, Language.FR), "Sadida"},
                {(PlayableClass.Sacrieur, Language.FR), "Sacrieur"},
                {(PlayableClass.Pandawa, Language.FR), "Pandawa"},
                
                {(PlayableClass.Feca, Language.EN), "Feca"},
                {(PlayableClass.Osamodas, Language.EN), "Osamodas"},
                {(PlayableClass.Enutrof, Language.EN), "Enutrof"},
                {(PlayableClass.Sram, Language.EN), "Sram"},
                {(PlayableClass.Xelor, Language.EN), "Xelor"},
                {(PlayableClass.Ecaflip, Language.EN), "Ecaflip"},
                {(PlayableClass.Eniripsa, Language.EN), "Eniripsa"},
                {(PlayableClass.Iop, Language.EN), "Iop"},
                {(PlayableClass.Cra, Language.EN), "Cra"},
                {(PlayableClass.Sadida, Language.EN), "Sadida"},
                {(PlayableClass.Sacrieur, Language.EN), "Sacrier"},
                {(PlayableClass.Pandawa, Language.EN), "Pandawa"},
                
                {(PlayableClass.Feca, Language.ES), "Feca"},
                {(PlayableClass.Osamodas, Language.ES), "Osamodas"},
                {(PlayableClass.Enutrof, Language.ES), "Anutrof"},
                {(PlayableClass.Sram, Language.ES), "Sram"},
                {(PlayableClass.Xelor, Language.ES), "Xelor"},
                {(PlayableClass.Ecaflip, Language.ES), "Zurcarák"},
                {(PlayableClass.Eniripsa, Language.ES), "Aniripsa"},
                {(PlayableClass.Iop, Language.ES), "Yopuka"},
                {(PlayableClass.Cra, Language.ES), "Ocra"},
                {(PlayableClass.Sadida, Language.ES), "Sadida"},
                {(PlayableClass.Sacrieur, Language.ES), "Sacrógrito"},
                {(PlayableClass.Pandawa, Language.ES), "Pandawa"},
            };
        }

        if (EffectNames == null || EffectNames.Count == 0)
        {
            Console.WriteLine("INIT EFFECT NAMES!");
            EffectNames = new Dictionary<(EffectType, Language), string>()
            {
                // Main effects
                {(EffectType.Vitality, Language.FR), "Vitalité"},
                {(EffectType.Wisdom, Language.FR), "Sagesse"},
                {(EffectType.Strength, Language.FR), "Force"},
                {(EffectType.Intelligence, Language.FR), "Intelligence"},
                {(EffectType.Chance, Language.FR), "Chance"},
                {(EffectType.Agility, Language.FR ), "Agilité"},
                {(EffectType.ActionPoint, Language.FR), "PA"},
                {(EffectType.MovementPoint, Language.FR), "PM"},
                {(EffectType.Range, Language.FR), "PO"},
                {(EffectType.SummonLimit, Language.FR), "Invocation"},
                {(EffectType.CriticalHit, Language.FR), "CC"},
                {(EffectType.BonusHeal, Language.FR), "Soin"},
                {(EffectType.Prospecting, Language.FR), "Prospection"},
                {(EffectType.Pods, Language.FR), "Pods"},
                {(EffectType.Initiative, Language.FR), "Initiative"},
                {(EffectType.DamageReflection, Language.FR), "Renvoi de dommages"},
                {(EffectType.TrapDamage, Language.FR), "Dommages aux pièges"},
                {(EffectType.TrapPower, Language.FR), "% dommages aux pièges"},
                {(EffectType.FixedDamage, Language.FR), "Dommages"},
                {(EffectType.PercentageDamage, Language.FR), "% dommages"},
                {(EffectType.NeutralFixedResistance, Language.FR), "Rés Neutre"},
                {(EffectType.EarthFixedResistance, Language.FR), "Rés Terre"},
                {(EffectType.FireFixedResistance, Language.FR), "Rés Feu"},
                {(EffectType.WaterFixedResistance, Language.FR), "Rés Eau"},
                {(EffectType.AirFixedResistance, Language.FR), "Rés Air"},
                {(EffectType.NeutralPercentageResistance, Language.FR), "% rés Neutre"},
                {(EffectType.EarthPercentageResistance, Language.FR), "% rés Terre"},
                {(EffectType.FirePercentageResistance, Language.FR), "% rés Feu"},
                {(EffectType.WaterPercentageResistance, Language.FR), "% rés Eau"},
                {(EffectType.AirPercentageResistance, Language.FR), "% rés Air"},
                
                // Weapon Effects
                {(EffectType.HuntingWeapon, Language.FR), "Arme de chasse"},
                {(EffectType.NeutralDamage, Language.FR), "Dommages (neutre)"},
                {(EffectType.EarthDamage, Language.FR), "Dommages (terre)"},
                {(EffectType.FireDamage, Language.FR), "Dommages (feu)"},
                {(EffectType.WaterDamage, Language.FR), "Dommages (eau)"},
                {(EffectType.AirDamage, Language.FR), "Dommages (air)"},
                {(EffectType.NeutralLifeSteal, Language.FR), "Vol de vie (neutre)"},
                {(EffectType.EarthLifeSteal, Language.FR), "Vol de vie (terre)"},
                {(EffectType.FireLifeSteal, Language.FR), "Vol de vie (feu)"},
                {(EffectType.WaterLifeSteal, Language.FR), "Vol de vie (eau)"},
                {(EffectType.AirLifeSteal, Language.FR), "Vol de vie (air)"},
                {(EffectType.Heal, Language.FR), "PDV rendus"},
                {(EffectType.MinusActionPoint, Language.FR), "PA perdus à la cible"},
                
                // Other effects
                {(EffectType.EnhancesPetCapacity, Language.FR), "Augmente les capacités d'un familier"},
                
                //
                // English
                //
                // Main effects
                {(EffectType.Vitality, Language.EN), "Vitality"},
                {(EffectType.Wisdom, Language.EN), "Wisdom"},
                {(EffectType.Strength, Language.EN), "Strength"},
                {(EffectType.Intelligence, Language.EN), "Intelligence"},
                {(EffectType.Chance, Language.EN), "Chance"},
                {(EffectType.Agility, Language.EN), "Agility"},
                {(EffectType.ActionPoint, Language.EN), "AP"},
                {(EffectType.MovementPoint, Language.EN), "MP"},
                {(EffectType.Range, Language.EN), "Range"},
                {(EffectType.SummonLimit, Language.EN), "Summonable creatures"},
                {(EffectType.CriticalHit, Language.EN), "Critical Hits"},
                {(EffectType.BonusHeal, Language.EN), "Heals"},
                {(EffectType.Prospecting, Language.EN), "Prospecting"},
                {(EffectType.Pods, Language.EN), "Pods"},
                {(EffectType.Initiative, Language.EN), "Initiative"},
                {(EffectType.DamageReflection, Language.EN), "Reflected damage"},
                {(EffectType.TrapDamage, Language.EN), "Trap damage"},
                {(EffectType.TrapPower, Language.EN), "% trap damage"},
                {(EffectType.FixedDamage, Language.EN), "Damage"},
                {(EffectType.PercentageDamage, Language.EN), "% damage"},
                {(EffectType.NeutralFixedResistance, Language.EN), "Neutral res"},
                {(EffectType.EarthFixedResistance, Language.EN), "Earth res"},
                {(EffectType.FireFixedResistance, Language.EN), "Fire res"},
                {(EffectType.WaterFixedResistance, Language.EN), "Water res"},
                {(EffectType.AirFixedResistance, Language.EN), "Air res"},
                {(EffectType.NeutralPercentageResistance, Language.EN), "% neutral res"},
                {(EffectType.EarthPercentageResistance, Language.EN), "% earth res"},
                {(EffectType.FirePercentageResistance, Language.EN), "% fire res"},
                {(EffectType.WaterPercentageResistance, Language.EN), "% water res"},
                {(EffectType.AirPercentageResistance, Language.EN), "% air res"},
                
                // Weapon Effects
                {(EffectType.HuntingWeapon, Language.EN), "Hunting weapon"},
                {(EffectType.NeutralDamage, Language.EN), "Damage (neutral)"},
                {(EffectType.EarthDamage, Language.EN), "Damage (earth)"},
                {(EffectType.FireDamage, Language.EN), "Damage (fire)"},
                {(EffectType.WaterDamage, Language.EN), "Damage (water)"},
                {(EffectType.AirDamage, Language.EN), "Damage (air)"},
                {(EffectType.NeutralLifeSteal, Language.EN), "Steals (neutral)"},
                {(EffectType.EarthLifeSteal, Language.EN), "Steals (earth)"},
                {(EffectType.FireLifeSteal, Language.EN), "Steals (fire)"},
                {(EffectType.WaterLifeSteal, Language.EN), "Steals (water)"},
                {(EffectType.AirLifeSteal, Language.EN), "Steals (air)"},
                {(EffectType.Heal, Language.EN), "HP restored"},
                {(EffectType.MinusActionPoint, Language.EN), "Lost AP for the target"},
                
                // Other effects
                {(EffectType.EnhancesPetCapacity, Language.EN), "Increases the capacity of a pet"},
                
                //
                // Spanish
                //
                // Main effects
                {(EffectType.Vitality, Language.ES), "Vitalidad"},
                {(EffectType.Wisdom, Language.ES), "Sabiduría"},
                {(EffectType.Strength, Language.ES), "Fuerza"},
                {(EffectType.Intelligence, Language.ES), "Inteligencia"},
                {(EffectType.Chance, Language.ES), "Suerte"},
                {(EffectType.Agility, Language.ES), "Agilidad"},
                {(EffectType.ActionPoint, Language.ES), "PA"},
                {(EffectType.MovementPoint, Language.ES), "PM"},
                {(EffectType.Range, Language.ES), "Alcance"},
                {(EffectType.SummonLimit, Language.ES), "Criaturas invocables"},
                {(EffectType.CriticalHit, Language.ES), "Golpes críticos"},
                {(EffectType.BonusHeal, Language.ES), "Curaciones"},
                {(EffectType.Prospecting, Language.ES), "Prospección"},
                {(EffectType.Pods, Language.ES), "Pods"},
                {(EffectType.Initiative, Language.ES), "Iniciativa"},
                {(EffectType.DamageReflection, Language.ES), "Reenvía daños"},
                {(EffectType.TrapDamage, Language.ES), "Daños con las trampas"},
                {(EffectType.TrapPower, Language.ES), "% de daños con las trampas"},
                {(EffectType.FixedDamage, Language.ES), "Daños"},
                {(EffectType.PercentageDamage, Language.ES), "% daños"},
                {(EffectType.NeutralFixedResistance, Language.ES), "Res neutral"},
                {(EffectType.EarthFixedResistance, Language.ES), "Res fuerza"},
                {(EffectType.FireFixedResistance, Language.ES), "Res fuego"},
                {(EffectType.WaterFixedResistance, Language.ES), "Res agua"},
                {(EffectType.AirFixedResistance, Language.ES), "Res aire"},
                {(EffectType.NeutralPercentageResistance, Language.ES), "% res neutral"},
                {(EffectType.EarthPercentageResistance, Language.ES), "% res fuerza"},
                {(EffectType.FirePercentageResistance, Language.ES), "% res fuego"},
                {(EffectType.WaterPercentageResistance, Language.ES), "% res agua"},
                {(EffectType.AirPercentageResistance, Language.ES), "% res aire"},
                
                // Weapon Effects
                 {(EffectType.HuntingWeapon, Language.ES), "Arma de caza"},
                {(EffectType.NeutralDamage, Language.ES), "Daños (neutrale)"},
                {(EffectType.EarthDamage, Language.ES), "Daños (earth)"},
                {(EffectType.FireDamage, Language.ES), "Daños (fire)"},
                {(EffectType.WaterDamage, Language.ES), "Daños (water)"},
                {(EffectType.AirDamage, Language.ES), "Daños (air)"},
                {(EffectType.NeutralLifeSteal, Language.ES), "Roba (neutral)"},
                {(EffectType.EarthLifeSteal, Language.ES), "Roba (earth)"},
                {(EffectType.FireLifeSteal, Language.ES), "Roba (fire)"},
                {(EffectType.WaterLifeSteal, Language.ES), "Roba (water)"},
                {(EffectType.AirLifeSteal, Language.ES), "Roba (air)"},
                {(EffectType.Heal, Language.ES), "HP restored"},
                {(EffectType.MinusActionPoint, Language.ES), "Lost AP for the target"},
                
                // Other effects
                {(EffectType.EnhancesPetCapacity, Language.ES), "Increases the capacity of a pet"}
            };
            Console.WriteLine($"EffectNames.Count = {EffectNames.Count}");
        }

        if (ConditionTypeNames == null || ConditionTypeNames.Count == 0)
        {
            ConditionTypeNames = new Dictionary<(ConditionType, Language), string>()
            {
                //
                // FR
                //
                {(ConditionType.CharacterLevel, Language.FR), "Niveau"},
                {(ConditionType.Class, Language.FR), "Classe"},
                {(ConditionType.Job, Language.FR), "Métier"},
                {(ConditionType.InZone, Language.FR), "Se trouver dans la zone"},
                {(ConditionType.Alignment, Language.FR), "Alignement"},
                {(ConditionType.AlignmentLevel, Language.FR), "Niveau d'alignement"},
                {(ConditionType.PvpRank, Language.FR), "Grade"},
                {(ConditionType.SubscribtionStatus, Language.FR), "Abonné"},
                {(ConditionType.Gift, Language.FR), "Don"},
                {(ConditionType.CharacterName, Language.FR), "Nom"},
                {(ConditionType.Gender, Language.FR), "Sexe"},
                
                //
                // EN
                //
                {(ConditionType.CharacterLevel, Language.EN), "Level"},
                {(ConditionType.Class, Language.EN), "Class"},
                {(ConditionType.Job, Language.EN), "Profession"},
                {(ConditionType.InZone, Language.EN), "Be in the zone"},
                {(ConditionType.Alignment, Language.EN), "Alignment"},
                {(ConditionType.AlignmentLevel, Language.EN), "Alignment level"},
                {(ConditionType.PvpRank, Language.EN), "Rank"},
                {(ConditionType.SubscribtionStatus, Language.EN), "Subscription"},
                {(ConditionType.Gift, Language.EN), "Gift"},
                {(ConditionType.CharacterName, Language.EN), "Name"},
                {(ConditionType.Gender, Language.EN), "Gender"},
                
                //
                // ES
                //
                {(ConditionType.CharacterLevel, Language.ES), "Nivel"},
                {(ConditionType.Class, Language.ES), "Clase"},
                {(ConditionType.Job, Language.ES), "Oficio"},
                {(ConditionType.InZone, Language.ES), "Estar en la zona"},
                {(ConditionType.Alignment, Language.ES), "Alineación"},
                {(ConditionType.AlignmentLevel, Language.ES), "Nivel de alineación"},
                {(ConditionType.PvpRank, Language.ES), "Grado"},
                {(ConditionType.SubscribtionStatus, Language.ES), "Abonado"},
                {(ConditionType.Gift, Language.ES), "Don"},
                {(ConditionType.CharacterName, Language.ES), "Nombre"},
                {(ConditionType.Gender, Language.ES), "Sexo"},
            };
        }

        if (AlignmentNames == null || AlignmentNames.Count == 0)
        {
            AlignmentNames = new Dictionary<(Alignment, Language), string>()
            {
                {(Alignment.Neutral, Language.FR), "Neutre"},
                {(Alignment.Bonta, Language.FR), "Bontarien"},
                {(Alignment.Brakmar, Language.FR), "Brakmarien"},
                {(Alignment.Mercenary, Language.FR), "Mercenaire"},
                
                {(Alignment.Neutral, Language.EN), "Neutral"},
                {(Alignment.Bonta, Language.EN), "Bontarian"},
                {(Alignment.Brakmar, Language.EN), "Brakmarian"},
                {(Alignment.Mercenary, Language.EN), "Mercenary"},
                
                {(Alignment.Neutral, Language.ES), "Neutral"},
                {(Alignment.Bonta, Language.ES), "Bontariano"},
                {(Alignment.Brakmar, Language.ES), "Brakmariano"},
                {(Alignment.Mercenary, Language.ES), "Mercenario"},
            };
        }

        if (GenderNames == null || GenderNames.Count == 0)
        {
            GenderNames = new Dictionary<(Gender, Language), string>()
            {
                { (Gender.Male, Language.FR), "Male" },
                { (Gender.Male, Language.EN), "Male" },
                { (Gender.Male, Language.ES), "Masculino" },
                { (Gender.Female, Language.FR), "Femelle" },
                { (Gender.Female, Language.EN), "Female" },
                { (Gender.Female, Language.ES), "Femenino" }
            };
        }
    }
    
    public static Dictionary<(Gender, Language), string>? GenderNames { get; }

    public static Dictionary<(ItemType, Language), string>? ItemTypeNames { get; }
    
    public static Dictionary<(Ecosystem, Language), string>? EcosystemNames { get; }

    public static Dictionary<(Breed, Language), string>? BreedNames { get; }
    
    public static Dictionary<(CardFamily, Language), string>? CardFamilyNames { get; }
    
    public static Dictionary<(PlayableClass, Language), string>? PlayableClassNames { get; }
    
    public static Dictionary<(Alignment, Language), string>? AlignmentNames { get; }
    
    public static Dictionary<(EffectType, Language), string>? EffectNames { get; }
    
    public static Dictionary<(ConditionType, Language), string>? ConditionTypeNames { get; }

    // public static Dictionary<(SubArea, Language), string> SubAreaNames = new()
    // {
    //     // English names
    //     {(SubArea.TheZothDoorKeepers, Language.EN), "The Zoth Door Keepers"},
    //     {(SubArea.SkeunkHideout, Language.EN), "Skeunk Hideout"},
    //     {(SubArea.AbandonedRailway, Language.EN), "Abandoned Railway"},
    //     {(SubArea.AerdalaPrism, Language.EN), "Aerdala Prism"},
    //     {(SubArea.AgonyVhelley, Language.EN), "Agony Valley"},
    //     {(SubArea.AkwadalaPrism, Language.EN), "Akwadala Prism"},
    //     {(SubArea.Amakna, Language.EN), "Amakna"},
    //     {(SubArea.AmaknaCastleGobbalBreedingStation, Language.EN), "Amakna Castle Gobbal Breeding Station"},
    //     {(SubArea.AmanknaCastleRatDungeon, Language.EN), "Amakna Castle Rat Dungeon"},
    //     {(SubArea.AmaknaCastleTunnel, Language.EN), "Amakna Castle Tunnel"},
    //     {(SubArea.AsseCoast, Language.EN), "Asse Coast"},
    //     {(SubArea.AstrubCity, Language.EN), "Astrub City"},
    //     {(SubArea.AstrubDeepTunnel, Language.EN), "Astrub Deep Tunnel"},
    //     {(SubArea.AstrubFields, Language.EN), "Astrub Fields"},
    //     {(SubArea.AstrubForest, Language.EN), "Astrub Forest"}, 
    //     {(SubArea.AstrubMeadows, Language.EN), "Astrub Meadows"},
    //     {(SubArea.AstrubMines, Language.EN), "Astrub Mines"},
    //     {(SubArea.AstrubRockyInlet, Language.EN), "Astrub Rocky Inlet"},
    //     {(SubArea.AstrubTunnel, Language.EN), "Astrub Tunnel"},
    //     {(SubArea.BakersQuarter, Language.EN), "Baker's Quarter"},
    //     {(SubArea.BanditTerritory, Language.EN), "Bandit Territory"},
    //     {(SubArea.BherbsGully, Language.EN), "Bherb's Gully"},
    //     {(SubArea.BlopDungeon, Language.EN), "Blop Dungeon"},
    //     {(SubArea.Bonta, Language.EN), "Bonta"},
    //     {(SubArea.BontaCemetery, Language.EN), "Bonta Cemetery"},
    //     {(SubArea.BontaRatDungeon, Language.EN), "Bonta Rat Dungeon"},
    //     {(SubArea.BontaSewers, Language.EN), "Bonta Sewers"},
    //     {(SubArea.BorderOfAerdala, Language.EN), "Border of Aerdala"},
    //     {(SubArea.BorderOfAkwadala, Language.EN), "Border of Akwadala"},
    //     {(SubArea.BorderOfFeudala, Language.EN), "Border of Feudala"},
    //     {(SubArea.BorderOfTerrdala, Language.EN), "Border of Terrdala"},
    //     {(SubArea.BottomlessPeatBog, Language.EN), "Bottomless Peat Bog"},
    //     {(SubArea.BottomlessSwamps, Language.EN), "Bottomless Swamps"},
    //     {(SubArea.Brakmar, Language.EN), "Brakmar"},
    //     {(SubArea.BrakmarFrontage, Language.EN), "Brakmar Frontage"},
    //     {(SubArea.BrakmarRatDungen, Language.EN), "Brakmar Rat Dungeon"},
    //     {(SubArea.BrakmarSewers, Language.EN), "Brakmar Sewers"},
    //     {(SubArea.BrouceBoulgourgsClearing, Language.EN), "Brouce Boulgourgs Clearing"},
    //     {(SubArea.ButchersQuarter, Language.EN), "Butcher's Quarter"},
    //     {(SubArea.BworkDungeon, Language.EN), "Bwork Dungeon"},
    //     {(SubArea.CampOfTheOneArmedBandits, Language.EN), "Camp of the One-Armed Bandits"},
    //     {(SubArea.CaniaBay, Language.EN), "Cania Bay"},
    //     {(SubArea.CaniaForest, Language.EN), "Cania Forest"},
    //     {(SubArea.CaniaMassif, Language.EN), "Cania Massif"},
    //     {(SubArea.CaniaPlain, Language.EN), "Cania Plain"},
    //     {(SubArea.Canidae, Language.EN), "Canidae"},
    //     {(SubArea.CastawaysIsland, Language.EN), "Castaway's Island"},
    //     {(SubArea.CemeteryOfHeroes, Language.EN), "Cemetery of Heroes"},
    //     {(SubArea.CemeteryOfTheTortured, Language.EN), "Cemetery of the Tortured"},
    //     {(SubArea.CooralBeach, Language.EN), "Cooral Beach"},
    //     {(SubArea.CracklerDungeon, Language.EN), "Crackler Dungeon"},
    //     {(SubArea.CracklerMountain, Language.EN), "Crackler Mountain"},
    //     {(SubArea.DarkJungle, Language.EN), "Dark Jungle"},
    //     {(SubArea.DarkTreechnidForest, Language.EN), "Dark Treechnid Forest"},
    //     {(SubArea.DopplePrism, Language.EN), "Dopple Prism"},
    //     {(SubArea.DoppleTraining, Language.EN), "Dopple Training"},
    //     {(SubArea.DoppleVillage, Language.EN), "Dopple Village"},
    //     {(SubArea.DreggonTunnel, Language.EN), "Dreggon Tunnel"},
    //     {(SubArea.DreggonVillage, Language.EN), "Dreggon Village"},
    //     {(SubArea.EdgeOfBonta, Language.EN), "Edge of Bonta"},
    //     {(SubArea.EdgeOfTheEvilForest, Language.EN), "Edge of the Evil Forest"},
    //     {(SubArea.EdgeOfTheMilicluster, Language.EN), "Edge of the Milicluster"},
    //     {(SubArea.EdgeOfTheTreechnidForest, Language.EN), "Edge of the Treechnid Forest"},
    //     {(SubArea.EltnegWood, Language.EN), "Eltneg Wood"},
    //     {(SubArea.EnchantedLakes, Language.EN), "Enchanted Lakes"},
    //     {(SubArea.FeudalaPrism, Language.EN), "Feudala Prism"},
    //     {(SubArea.FeudalaVillage, Language.EN), "Feudala Village"},
    //     {(SubArea.FieldDungeon, Language.EN), "Field Dungeon"},
    //     {(SubArea.FirefouxDungeon, Language.EN), "Firefoux Dungeon"},
    //     {(SubArea.FortificationOfBonta, Language.EN), "Fortification of Bonta"},
    //     {(SubArea.FungusCavern, Language.EN), "Fungus Cavern"},
    //     {(SubArea.FungusDungeon, Language.EN), "Fungus Dungeon"},
    //     {(SubArea.GisgoulTheDevastatedVillage, Language.EN), "Gisgoul The Devastated Village"},
    //     {(SubArea.GobballCorner, Language.EN), "Gobball Corner"},
    //     {(SubArea.GobballDungeon, Language.EN), "Gobball Dungeon"},
    //     {(SubArea.GrassPlains, Language.EN), "Grass Plains"},
    //     {(SubArea.GrottoHesque, Language.EN), "Grotto Hesque"},
    //     {(SubArea.HandymensQuarter, Language.EN), "Handymen's Quarter"},
    //     {(SubArea.HiddenLaboratory, Language.EN), "Hidden Laboratory"},
    //     {(SubArea.HoldOfOtomaisArk, Language.EN), "Hold of Otomai's Ark"},
    //     {(SubArea.IlyzaellesLookout, Language.EN), "Ilyzaelle's Lookout"},
    //     {(SubArea.ImpPrism, Language.EN), "Imp Prism"},
    //     {(SubArea.ImpVillage, Language.EN), "Imp Village"},
    //     {(SubArea.JewellersQuarter, Language.EN), "Jeweller's Quarter"},
    //     {(SubArea.KaliptusForest, Language.EN), "Kaliptus Forest"},
    //     {(SubArea.KawaiiRiver, Language.EN), "Kawaii River"},
    //     {(SubArea.KimbosCanopy, Language.EN), "Kimbo's Canopy"},
    //     {(SubArea.KitsouDungeon, Language.EN), "Kitsou Dungeon"},
    //     {(SubArea.KoolichCavern, Language.EN), "Koolich Cavern"},
    //     {(SubArea.KwismasDeungeon, Language.EN), "Kwismas Dungeon"},
    //     {(SubArea.KwismasIsland, Language.EN), "Kwismas Island"},
    //     {(SubArea.LabyrinthOfTheMinotoror, Language.EN), "Labyrinth of the Minotoror"},
    //     {(SubArea.Lake, Language.EN), "Lake"},
    //     {(SubArea.LarvaDungeon, Language.EN), "Larva Dungeon"},
    //     {(SubArea.LittleSlopeGrove, Language.EN), "Little Slope Grove"},
    //     {(SubArea.LordCrowsLibrary, Language.EN), "Lord Crow's Library"},
    //     {(SubArea.LousyPigPlain, Language.EN), "Lousy Pig Plain"},
    //     {(SubArea.LowCracklerMountain, Language.EN), "Low Crackler Mountain"},
    //     {(SubArea.LumberjacksQuarter, Language.EN), "Lumberjack's Quarter"},
    //     {(SubArea.MadrestamHarbour, Language.EN), "Madrestam Harbour"},
    //     {(SubArea.MilitiaDistrict, Language.EN), "Militia District"},
    //     {(SubArea.MinotororIsland, Language.EN), "Minotoror Island"},
    //     {(SubArea.MoonBeach, Language.EN), "Moon Beach"},
    //     {(SubArea.MushdCorner, Language.EN), "Mushd Corner"},
    //     {(SubArea.MysteriousTunnel, Language.EN), "Mysterious Tunnel"},
    //     {(SubArea.NauseatingSwamps, Language.EN), "Nauseating Swamps"},
    //     {(SubArea.NeutralPandala, Language.EN), "Neutral Pandala"},
    //     {(SubArea.NolifisIsland, Language.EN), "Nolifis Island"},
    //     {(SubArea.OtomaisArk, Language.EN), "Otomai's Ark"},
    //     {(SubArea.PandalaForest, Language.EN), "Pandala Forest"},
    //     {(SubArea.PandalaVillage, Language.EN), "Pandala Village"},
    //     {(SubArea.PandikazeHideout, Language.EN), "Pandikaze Hideout"},
    //     {(SubArea.PassageToBrakmar, Language.EN), "Passage to Brakmar"},
    //     {(SubArea.PorcoTerritory, Language.EN), "Porco Territory"},
    //     {(SubArea.PrimitiveCemetery, Language.EN), "Primitive Cemetery"},
    //     {(SubArea.PutridPeatBog, Language.EN), "Putrid Peat Bog"},
    //     {(SubArea.QuTansSanctuary, Language.EN), "Qu'Tan's Sanctuary"},
    //     {(SubArea.RoadToBonta, Language.EN), "Road to Bonta"},
    //     {(SubArea.RockyPeaks, Language.EN), "Rocky Peaks"},
    //     {(SubArea.RockyPlains, Language.EN), "Rocky Plains"},
    //     {(SubArea.SandDungeon, Language.EN), "Sand Dungeon"},
    //     {(SubArea.ScaraleafDungeon, Language.EN), "Scaraleaf Dungeon"},
    //     {(SubArea.Sea, Language.EN), "Sea"},
    //     {(SubArea.SidimoteMoor, Language.EN), "Sidimote Moor"},
    //     {(SubArea.SkeletonWabbitIsland, Language.EN), "Skeleton Wabbit Island"},
    //     {(SubArea.SmallWabbitIsland, Language.EN), "Small Wabbit Island"},
    //     {(SubArea.SmithsQuarter, Language.EN), "Smith's Quarter"},
    //     {(SubArea.Sufokia, Language.EN), "Sufokia"},
    //     {(SubArea.SufokianGulfShoreline, Language.EN), "Sufokian Gulf Shoreline"},
    //     {(SubArea.SurroundingsOfAstrub, Language.EN), "Surroundings of Astrub"},
    //     {(SubArea.TailorsQuarter, Language.EN), "Tailor's Quarter"},
    //     {(SubArea.Tainela, Language.EN), "Tainela"},
    //     {(SubArea.TerrdalaPrism, Language.EN), "Terrdala Prism"},
    //     {(SubArea.TheAmaknaForest, Language.EN), "The Amakna Forest"},
    //     {(SubArea.TheBworkCamp, Language.EN), "The Bwork Camp"},
    //     {(SubArea.TheCaniaFields, Language.EN), "The Cania Fields"},
    //     {(SubArea.TheCemetery, Language.EN), "The Cemetery"},
    //     {(SubArea.TheCountryside, Language.EN), "The Countryside"},
    //     {(SubArea.TheCradle, Language.EN), "The Cradle"},
    //     {(SubArea.TheCrowdDomain, Language.EN), "The Crowd Domain"},
    //     {(SubArea.TheCrypts, Language.EN), "The Crypts"},
    //     {(SubArea.TheDeepMoonJungle, Language.EN), "The Deep Moon Jungle"},
    //     {(SubArea.TheDragonPigsMaze, Language.EN), "The Dragon Pig's Maze"},
    //     {(SubArea.TheDreggonPeninsula, Language.EN), "The Dreggon Peninsula"},
    //     {(SubArea.TheDreggonsSanctuary, Language.EN), "The Dreggons Sanctuary"},
    //     {(SubArea.TheEvilForest, Language.EN), "The Evil Forest"},
    //     {(SubArea.TheGoblinCamp, Language.EN), "The Goblin Camp"},
    //     {(SubArea.TheIngalssesFields, Language.EN), "The Ingalsses Fields"},
    //     {(SubArea.TheJellyPeninsula, Language.EN), "The Jelly Peninsula"},
    //     {(SubArea.TheMilicluster, Language.EN), "The Milicluster"},
    //     {(SubArea.ThePirateBoat, Language.EN), "The Pirate Boat"},
    //     {(SubArea.TheRoadToMoon, Language.EN), "The Road to Moon"},
    //     {(SubArea.TheSwamp, Language.EN), "The Swamp"},
    //     {(SubArea.TheTempleOfCra, Language.EN), "The Temple of Cra"},
    //     {(SubArea.TheTempleOfEcaflip, Language.EN), "The Temple of Ecaflip"},
    //     {(SubArea.TheTempleOfEniripsa, Language.EN), "The Temple of Eniripsa"},
    //     {(SubArea.TheTempleOfEnutrof, Language.EN), "The Temple of Enutrof"},
    //     {(SubArea.TheTempleOfFeca, Language.EN), "The Temple of Feca"},
    //     {(SubArea.TheTempleOfIop, Language.EN), "The Temple of Iop"},
    //     {(SubArea.TheTempleOfPandawa, Language.EN), "The Temple of Pandawa"},
    //     {(SubArea.TheTempleOfOsamodas, Language.EN), "The Temple of Osamodas"},
    //     {(SubArea.TheTempleOfSacrier, Language.EN), "The Temple of Sacrier"},
    //     {(SubArea.TheTempleOfSadida, Language.EN), "The Temple of Sadida"},
    //     {(SubArea.TheTempleOfSram, Language.EN), "The Temple of Sram"},
    //     {(SubArea.TheTempleOfXelor, Language.EN), "The Temple of Xelor"},
    //     {(SubArea.TheTerritoryOfTheBandits, Language.EN), "The Territory of the Bandits"},
    //     {(SubArea.TheVillage, Language.EN), "The Village"},
    //     {(SubArea.TofuCorner, Language.EN), "Tofu Corner"},
    //     {(SubArea.TofuDungeon, Language.EN), "Tofu Dungeon"},
    //     {(SubArea.TreeKeeholoVillage, Language.EN), "Tree Keeholo Village"},
    //     {(SubArea.TreeKeeholoTrunk, Language.EN), "Tree Keeholo Trunk"},
    //     {(SubArea.TreechnidDungeon, Language.EN), "Treechnid Dungeon"},
    //     {(SubArea.TreechnidForest, Language.EN), "Treechnid Forest"},
    //     {(SubArea.Tunnel, Language.EN), "Tunnel"},
    //     {(SubArea.TynrilLaboratory, Language.EN), "Tynril Laboratory"},
    //     {(SubArea.WabbitCastleIsland, Language.EN), "Wabbit Castle Island"},
    //     {(SubArea.WabbitCastle, Language.EN), "Wabbit Castle"},
    //     {(SubArea.WabbitTunnels, Language.EN), "Wabbit Tunnels"},
    //     {(SubArea.WildCanyon, Language.EN), "Wild Canyon"},
    //     {(SubArea.WildDragoturkeyTerritory, Language.EN), "Wild Dragoturkey Territory"},
    //     {(SubArea.ZothPrism, Language.EN), "Zoth Prism"},
    //     {(SubArea.ZothVillage, Language.EN), "Zoth Village"},
    // };
}