namespace DofusRetroAPI.Entities.Enums;

public enum EffectType
{
    // All Items Effects
    Experience,
    Vitality,
    Wisdom,
    Strength,
    Intelligence,
    Chance,
    Agility,
    ActionPoint,
    MovementPoint,
    Range,
    SummonLimit,
    CriticalHit,
    BonusHeal,
    Prospecting,
    Pods,
    Initiative,
    DamageReflection,
    TrapDamage,
    TrapPower,
    Damage,
    Power,
    NeutralResistance,
    EarthResistance,
    FireResistance,
    WaterResistance,
    AirResistance,
    NeutralPercentageResistance,
    EarthPercentageResistance,
    FirePercentageResistance,
    WaterPercentageResistance,
    AirPercentageResistance,
    
    // Weapon Effects
    NeutralDamage,
    EarthDamage,
    FireDamage,
    WaterDamage,
    AirDamage,
    NeutralLifeSteal,
    EarthLifeSteal,
    FireLifeSteal,
    WaterLifeSteal,
    AirLifeSteal,
    Heal,
    MinusActionPoint
}