namespace DofusRetroAPI.Entities.Enums;

public static class Localization
{
    public static Dictionary<(EquipmentType, Language), string> EquipmentTypeNames = new()
    {
        // French Localization
        {(EquipmentType.Hat, Language.FR), "Chapeau"},
        {(EquipmentType.Cloak, Language.FR), "Cape"},
        {(EquipmentType.Backpack, Language.FR), "Sac à dos"},
        {(EquipmentType.Amulet, Language.FR), "Amulette"},
        {(EquipmentType.Belt, Language.FR), "Ceinture"},
        {(EquipmentType.Boots, Language.FR), "Bottes"},
        {(EquipmentType.Dofus, Language.FR), "Dofus"},
        {(EquipmentType.Pet, Language.FR), "Familier"},
        {(EquipmentType.Dragoturkey, Language.FR), "Dragodinde"},
        {(EquipmentType.SoulStone, Language.FR), "Pierre d'âme"},
        {(EquipmentType.CapturingNet, Language.FR), "Filet de capture"},
        {(EquipmentType.Staff, Language.FR), "Bâton"},
        {(EquipmentType.Bow, Language.FR), "Arc"},
        {(EquipmentType.Wand, Language.FR), "Baguette"},
        {(EquipmentType.Sword, Language.FR), "Épée"},
        {(EquipmentType.Hammer, Language.FR), "Marteau"},
        {(EquipmentType.Shovel, Language.FR), "Pelle"},
        {(EquipmentType.Dagger, Language.FR), "Dague"},
        {(EquipmentType.Axe, Language.FR), "Hache"},
        {(EquipmentType.Tool, Language.FR), "Outil"},
        {(EquipmentType.Pickaxe, Language.FR), "Pioche"},
        {(EquipmentType.Scythe, Language.FR), "Faux"},
        {(EquipmentType.Crossbow, Language.FR), "Arbalète"},
        {(EquipmentType.MagicWeapon, Language.FR), "Arme magique"},
        {(EquipmentType.Ring, Language.FR), "Anneau"},
        {(EquipmentType.Shield, Language.FR), "Bouclier"},

        // English Localization
        {(EquipmentType.Hat, Language.EN), "Hat"},
        {(EquipmentType.Cloak, Language.EN), "Cloak"},
        {(EquipmentType.Backpack, Language.EN), "Backpack"},
        {(EquipmentType.Amulet, Language.EN), "Amulet"},
        {(EquipmentType.Belt, Language.EN), "Belt"},
        {(EquipmentType.Boots, Language.EN), "Boots"},
        {(EquipmentType.Dofus, Language.EN), "Dofus"},
        {(EquipmentType.Pet, Language.EN), "Pet"},
        {(EquipmentType.Dragoturkey, Language.EN), "Dragoturkey"},
        {(EquipmentType.SoulStone, Language.EN), "Soul stone"},
        {(EquipmentType.CapturingNet, Language.EN), "Capturing net"},
        {(EquipmentType.Staff, Language.EN), "Staff"},
        {(EquipmentType.Bow, Language.EN), "Bow"},
        {(EquipmentType.Wand, Language.EN), "Wand"},
        {(EquipmentType.Sword, Language.EN), "Sword"},
        {(EquipmentType.Hammer, Language.EN), "Hammer"},
        {(EquipmentType.Shovel, Language.EN), "Shovel"},
        {(EquipmentType.Dagger, Language.EN), "Daggers"},
        {(EquipmentType.Axe, Language.EN), "Axe"},
        {(EquipmentType.Tool, Language.EN), "Tool"},
        {(EquipmentType.Pickaxe, Language.EN), "Pickaxe"},
        {(EquipmentType.Scythe, Language.EN), "Scythe"},
        {(EquipmentType.Crossbow, Language.EN), "Crossbow"},
        {(EquipmentType.MagicWeapon, Language.EN), "MagicWeapon"},
        {(EquipmentType.Ring, Language.EN), "Ring"},
        {(EquipmentType.Shield, Language.EN), "Shield"},

        // Spanish Localization
        {(EquipmentType.Hat, Language.ES), "Sombrero"},
        {(EquipmentType.Cloak, Language.ES), "Capa"},
        {(EquipmentType.Backpack, Language.ES), "Mochila"},
        {(EquipmentType.Amulet, Language.ES), "Amulette"},
        {(EquipmentType.Belt, Language.ES), "Cinturón"},
        {(EquipmentType.Boots, Language.ES), "Botas"},
        {(EquipmentType.Dofus, Language.ES), "Dofus"},
        {(EquipmentType.Pet, Language.ES), "Mascota"},
        {(EquipmentType.Dragoturkey, Language.ES), "Dragopavo"},
        {(EquipmentType.SoulStone, Language.ES), "Piedra de alma"},
        {(EquipmentType.CapturingNet, Language.ES), "Red de captura"},
        {(EquipmentType.Staff, Language.ES), "Bastón"},
        {(EquipmentType.Bow, Language.ES), "Arco"},
        {(EquipmentType.Wand, Language.ES), "Varita"},
        {(EquipmentType.Sword, Language.ES), "Espada"},
        {(EquipmentType.Hammer, Language.ES), "Martillo"},
        {(EquipmentType.Shovel, Language.ES), "Pala"},
        {(EquipmentType.Dagger, Language.ES), "Daga"},
        {(EquipmentType.Axe, Language.ES), "Hacha"},
        {(EquipmentType.Tool, Language.ES), "Herramienta"},
        {(EquipmentType.Pickaxe, Language.ES), "Pico"},
        {(EquipmentType.Scythe, Language.ES), "Guadaña"},
        {(EquipmentType.Crossbow, Language.ES), "Ballesta"},
        {(EquipmentType.MagicWeapon, Language.ES), "Varita"},
        {(EquipmentType.Ring, Language.ES), "Anillo"},
        {(EquipmentType.Shield, Language.ES), "Escudo"},
    };

    public static Dictionary<(ConsumableType, Language), string> ConsumableTypeNames = new()
    {
        // French names
        {(ConsumableType.Bread, Language.FR), "Pain"},
        {(ConsumableType.EdibleFish, Language.FR), "Poisson comestible"},
        {(ConsumableType.EdibleMeat, Language.FR), "Viande comestible"},
        {(ConsumableType.Candy, Language.FR), "Friandise"},
        {(ConsumableType.Beer, Language.FR), "Bière"},
        {(ConsumableType.Drink, Language.FR), "Boisson"},
        {(ConsumableType.Potion, Language.FR), "Potion"},
        {(ConsumableType.SkillLossPotion, Language.FR), "Potion d'oubli de maîtrise"},
        {(ConsumableType.UnlearningPotionForProfession, Language.FR), "Potion d'oubli de métier"},
        {(ConsumableType.ForgetfulnessPotion, Language.FR), "Potion d'oubli de sort"},
        {(ConsumableType.ForgetfulnessPotionForCollectors, Language.FR), "Potion d'oubli de percepteur"},
        {(ConsumableType.PetPotion, Language.FR), "Potion de familier"},
        {(ConsumableType.Dyeing, Language.FR), "Teinture"},
        {(ConsumableType.GiftItem, Language.FR), "Objet de dons"},
        {(ConsumableType.Document, Language.FR), "Document"},
        {(ConsumableType.Skill, Language.FR), "Maîtrise"},
        {(ConsumableType.ExperienceScroll, Language.FR), "Parchemin d'expérience"},
        {(ConsumableType.CharacteristicScroll, Language.FR), "Parchemin de caractéristique"},
        {(ConsumableType.SpellScroll, Language.FR), "Parchemin de sort"},
        {(ConsumableType.MountCertificate, Language.FR), "Certificat de monture"},
        {(ConsumableType.BowKennelCertificate, Language.FR), "Certificat de mise en chenil"},
        {(ConsumableType.SeekerScroller, Language.FR), "Parchemin de recherche"},
        {(ConsumableType.SpiritGem, Language.FR), "Gemme spirituelle"},
        {(ConsumableType.BagOfResources, Language.FR), "Sac de ressources"},
        {(ConsumableType.PetEgg, Language.FR), "Oeuf de familier"},
        {(ConsumableType.FairyWork, Language.FR), "Fée d'artifice"},
        {(ConsumableType.MagicStone, Language.FR), "Pierre magique"},
        {(ConsumableType.Gift, Language.FR), "Cadeau"},
        {(ConsumableType.BreedingItem, Language.FR), "Objet d'élevage"},
        {(ConsumableType.UsableItem, Language.FR), "Objet utilisable"},
        {(ConsumableType.QuestItem, Language.FR), "Objet de quête"},
        {(ConsumableType.Prism, Language.FR), "Prisme"},
        {(ConsumableType.FragmentOfShushuSoul, Language.FR), "Fragment d'âme de Shushu"},
        
        // English names
        {(ConsumableType.Bread, Language.EN), "Bread"},
        {(ConsumableType.EdibleFish, Language.EN), "Edible fish"},
        {(ConsumableType.EdibleMeat, Language.EN), "Edible meat"},
        {(ConsumableType.Candy, Language.EN), "Candy"},
        {(ConsumableType.Beer, Language.EN), "Beer"},
        {(ConsumableType.Drink, Language.EN), "Drink"},
        {(ConsumableType.Potion, Language.EN), "Potion"},
        {(ConsumableType.SkillLossPotion, Language.EN), "Skill loss potion"},
        {(ConsumableType.UnlearningPotionForProfession, Language.EN), "Unlearning potion for profession"},
        {(ConsumableType.ForgetfulnessPotion, Language.EN), "Forgetfulness potion"},
        {(ConsumableType.ForgetfulnessPotionForCollectors, Language.EN), "Forgetfulness potion for collectors"},
        {(ConsumableType.PetPotion, Language.EN), "Pet potion"},
        {(ConsumableType.Dyeing, Language.EN), "Dyeing"},
        {(ConsumableType.GiftItem, Language.EN), "Gift item"},
        {(ConsumableType.Document, Language.EN), "Document"},
        {(ConsumableType.Skill, Language.EN), "Skill"},
        {(ConsumableType.ExperienceScroll, Language.EN), "Experience scroll"},
        {(ConsumableType.CharacteristicScroll, Language.EN), "Characteristic scroll"},
        {(ConsumableType.SpellScroll, Language.EN), "Spell scroll"},
        {(ConsumableType.MountCertificate, Language.EN), "Mount certificate"},
        {(ConsumableType.BowKennelCertificate, Language.EN), "Bow kennel certificate"},
        {(ConsumableType.SeekerScroller, Language.EN), "Seeker scroller"},
        {(ConsumableType.SpiritGem, Language.EN), "Spirit gem"},
        {(ConsumableType.BagOfResources, Language.EN), "Bag of resources"},
        {(ConsumableType.PetEgg, Language.EN), "Pet egg"},
        {(ConsumableType.FairyWork, Language.EN), "Fairywork"},
        {(ConsumableType.MagicStone, Language.EN), "Magic stone"},
        {(ConsumableType.Gift, Language.EN), "Gift"},
        {(ConsumableType.BreedingItem, Language.EN), "Breeding Item"},
        {(ConsumableType.UsableItem, Language.EN), "Usable item"},
        {(ConsumableType.QuestItem, Language.EN), "Quest item"},
        {(ConsumableType.Prism, Language.EN), "Prism"},
        {(ConsumableType.FragmentOfShushuSoul, Language.EN), "Fragment of Shushu soul"},
        
        // Spanish names
        {(ConsumableType.Bread, Language.ES), "Pan"},
        {(ConsumableType.EdibleFish, Language.ES), "Pescado comestible"},
        {(ConsumableType.EdibleMeat, Language.ES), "Carne comestible"},
        {(ConsumableType.Candy, Language.ES), "Golosina"},
        {(ConsumableType.Beer, Language.ES), "Cerveza"},
        {(ConsumableType.Drink, Language.ES), "Bebida"},
        {(ConsumableType.Potion, Language.ES), "Pócima"},
        {(ConsumableType.SkillLossPotion, Language.ES), "Pócima de olvido de dominio"},
        {(ConsumableType.UnlearningPotionForProfession, Language.ES), "Poción de olvido de oficio"},
        {(ConsumableType.ForgetfulnessPotion, Language.ES), "Poción de olvido de hechizo"},
        {(ConsumableType.ForgetfulnessPotionForCollectors, Language.ES), "Poción de olvido de recaudador"},
        {(ConsumableType.PetPotion, Language.ES), "Poción de mascota"},
        {(ConsumableType.Dyeing, Language.ES), "Tinte"},
        {(ConsumableType.GiftItem, Language.ES), "Objeto de dones"},
        {(ConsumableType.Document, Language.ES), "Documento"},
        {(ConsumableType.Skill, Language.ES), "Dominio"},
        {(ConsumableType.ExperienceScroll, Language.ES), "Pergamino de experiencia"},
        {(ConsumableType.CharacteristicScroll, Language.ES), "Pergamino de característica"},
        {(ConsumableType.SpellScroll, Language.ES), "Pergamino de hechizo"},
        {(ConsumableType.MountCertificate, Language.ES), "Certificado de montura"},
        {(ConsumableType.BowKennelCertificate, Language.ES), "Certificado de admisión en la petrera"},
        {(ConsumableType.SeekerScroller, Language.ES), "Pergamino de búsqueda"},
        {(ConsumableType.SpiritGem, Language.ES), "Gema espiritual"},
        {(ConsumableType.BagOfResources, Language.ES), "Sacos de recursos"},
        {(ConsumableType.PetEgg, Language.ES), "Huevo de mascota"},
        {(ConsumableType.FairyWork, Language.ES), "Hada artificial"},
        {(ConsumableType.MagicStone, Language.ES), "Piedra mágica"},
        {(ConsumableType.Gift, Language.ES), "Regalo"},
        {(ConsumableType.BreedingItem, Language.ES), "Objeto de cría"},
        {(ConsumableType.UsableItem, Language.ES), "Objeto utilizable"},
        {(ConsumableType.QuestItem, Language.ES), "Objeto de misión"},
        {(ConsumableType.Prism, Language.ES), "Prisma"},
        {(ConsumableType.FragmentOfShushuSoul, Language.ES), "Fragmento de alma de Fab'huritu"}
    };

    public static Dictionary<(ResourceType, Language), string> ResourceTypeNames = new()
    {
        // French names
        {(ResourceType.AlchemyEquipment, Language.FR), "Matériel  d'alchimie"},
        {(ResourceType.Alloy, Language.FR), "Alliage"},
        {(ResourceType.Bark, Language.FR), "Écorce"},
        {(ResourceType.Bone, Language.FR), "Os"},
        {(ResourceType.Bud, Language.FR), "Bourgeon"},
        {(ResourceType.Carapace, Language.FR), "Carapace"},
        {(ResourceType.Cereal, Language.FR), "Céréale"},
        {(ResourceType.Ear, Language.FR), "Oreille"},
        {(ResourceType.Egg, Language.FR), "Oeuf"},
        {(ResourceType.Eye, Language.FR), "Oeil"},
        {(ResourceType.Fabric, Language.FR), "Étoffe"},
        {(ResourceType.Feather, Language.FR), "Plume"},
        {(ResourceType.Fish, Language.FR), "Poisson"},
        {(ResourceType.Flour, Language.FR), "Farine"},
        {(ResourceType.Flower, Language.FR), "Fleur"},
        {(ResourceType.Fruit, Language.FR), "Fruit"},
        {(ResourceType.GuttedFish, Language.FR), "Poisson vidé"},
        {(ResourceType.Hair, Language.FR), "Poil"},
        {(ResourceType.Jelly, Language.FR), "Gelée"},
        {(ResourceType.Key, Language.FR), "Clef"},
        {(ResourceType.Leather, Language.FR), "Peau"},
        {(ResourceType.Leg, Language.FR), "Patte"},
        {(ResourceType.Meat, Language.FR), "Viande"},
        {(ResourceType.Metaria, Language.FR), "Metaria"},
        {(ResourceType.Oil, Language.FR), "Huile"},
        {(ResourceType.Ore, Language.FR), "Minerai"},
        {(ResourceType.PetGhost, Language.FR), "Fantôme de familier"},
        {(ResourceType.Plank, Language.FR), "Planche"},
        {(ResourceType.Powder, Language.FR), "Poudre"},
        {(ResourceType.PreciousStone, Language.FR), "Pierre précieuse"},
        {(ResourceType.PreservedMeat, Language.FR), "Viande conservée"},
        {(ResourceType.Resource, Language.FR), "Ressource"},
        {(ResourceType.Root, Language.FR), "Racine"},
        {(ResourceType.Seed, Language.FR), "Graine"},
        {(ResourceType.Shell, Language.FR), "Coquille"},
        {(ResourceType.Skin, Language.FR), "Peau"},
        {(ResourceType.SmithMagicPotion, Language.FR), "Potion de forgemagie"},
        {(ResourceType.SmithMagicRune, Language.FR), "Run de forgemagie"},
        {(ResourceType.Stone, Language.FR), "Pierre brute"},
        {(ResourceType.StuffedAnimal, Language.FR), "Peluche"},
        {(ResourceType.Tail, Language.FR), "Queue"},
        {(ResourceType.Vegetable, Language.FR), "Légume"},
        {(ResourceType.Wing, Language.FR), "Aile"},
        {(ResourceType.Wood, Language.FR), "Bois"},
        {(ResourceType.Wool, Language.FR), "Laine"},
        
        // English names
        {(ResourceType.AlchemyEquipment, Language.EN), "Alchemy equipment"},
        {(ResourceType.Alloy, Language.EN), "Alloy"},
        {(ResourceType.Bark, Language.EN), "Bark"},
        {(ResourceType.Bone, Language.EN), "Bone"},
        {(ResourceType.Bud, Language.EN), "Bud"},
        {(ResourceType.Carapace, Language.EN), "Carapace"},
        {(ResourceType.Cereal, Language.EN), "Cereal"},
        {(ResourceType.Ear, Language.EN), "Ear"},
        {(ResourceType.Egg, Language.EN), "Egg"},
        {(ResourceType.Eye, Language.EN), "Eye"},
        {(ResourceType.Fabric, Language.EN), "Fabric"},
        {(ResourceType.Feather, Language.EN), "Feather"},
        {(ResourceType.Fish, Language.EN), "Fish"},
        {(ResourceType.Flour, Language.EN), "Flour"},
        {(ResourceType.Flower, Language.EN), "Flower"},
        {(ResourceType.Fruit, Language.EN), "Fruit"},
        {(ResourceType.GuttedFish, Language.EN), "Gutted fish"},
        {(ResourceType.Hair, Language.EN), "Hair"},
        {(ResourceType.Jelly, Language.EN), "Jelly"},
        {(ResourceType.Key, Language.EN), "Key"},
        {(ResourceType.Leather, Language.EN), "Leather"},
        {(ResourceType.Leg, Language.EN), "Leg"},
        {(ResourceType.Meat, Language.EN), "Meat"},
        {(ResourceType.Metaria, Language.EN), "Metaria"},
        {(ResourceType.Oil, Language.EN), "Oil"},
        {(ResourceType.Ore, Language.EN), "Ore"},
        {(ResourceType.PetGhost, Language.EN), "Pet ghost"},
        {(ResourceType.Plank, Language.EN), "Plank"},
        {(ResourceType.Powder, Language.EN), "Powder"},
        {(ResourceType.PreciousStone, Language.EN), "Precious stone"},
        {(ResourceType.PreservedMeat, Language.EN), "Preserved meat"},
        {(ResourceType.Resource, Language.EN), "Resource"},
        {(ResourceType.Root, Language.EN), "Root"},
        {(ResourceType.Seed, Language.EN), "Seed"},
        {(ResourceType.Shell, Language.EN), "Shell"},
        {(ResourceType.Skin, Language.EN), "Skin"},
        {(ResourceType.SmithMagicPotion, Language.EN), "Smithmagic potion"},
        {(ResourceType.SmithMagicRune, Language.EN), "Smithmagic rune"},
        {(ResourceType.Stone, Language.EN), "Stone"},
        {(ResourceType.StuffedAnimal, Language.EN), "Stuffed animal"},
        {(ResourceType.Tail, Language.EN), "Tail"},
        {(ResourceType.Vegetable, Language.EN), "Vegetable"},
        {(ResourceType.Wing, Language.EN), "Wing"},
        {(ResourceType.Wood, Language.EN), "Wood"},
        {(ResourceType.Wool, Language.EN), "Wool"},

        // Spanish names
        {(ResourceType.AlchemyEquipment, Language.ES), "Material de alquimia"},
        {(ResourceType.Alloy, Language.ES), "Aleacion"},
        {(ResourceType.Bark, Language.ES), "Corteza"},
        {(ResourceType.Bone, Language.ES), "Hueso"},
        {(ResourceType.Bud, Language.ES), "Brote"},
        {(ResourceType.Carapace, Language.ES), "Carapazon"},
        {(ResourceType.Cereal, Language.ES), "Cereal"},
        {(ResourceType.Ear, Language.ES), "Oreja"},
        {(ResourceType.Egg, Language.ES), "Huevo"},
        {(ResourceType.Eye, Language.ES), "Ojo"},
        {(ResourceType.Fabric, Language.ES), "Tejido"},
        {(ResourceType.Feather, Language.ES), "Pluma"},
        {(ResourceType.Fish, Language.ES), "Pez"},
        {(ResourceType.Flour, Language.ES), "Harina"},
        {(ResourceType.Flower, Language.ES), "Flor"},
        {(ResourceType.Fruit, Language.ES), "Fruta"},
        {(ResourceType.GuttedFish, Language.ES), "Pescado vaciado"},
        {(ResourceType.Hair, Language.ES), "Pelo"},
        {(ResourceType.Jelly, Language.ES), "Gelatina"},
        {(ResourceType.Key, Language.ES), "Llave"},
        {(ResourceType.Leather, Language.ES), "Cuero"},
        {(ResourceType.Leg, Language.ES), "Pata"},
        {(ResourceType.Meat, Language.ES), "Carne"},
        {(ResourceType.Metaria, Language.ES), "Metaria"},
        {(ResourceType.Oil, Language.ES), "Aceite"},
        {(ResourceType.Ore, Language.ES), "Mineral"},
        {(ResourceType.PetGhost, Language.ES), "Fantasma de mascota"},
        {(ResourceType.Plank, Language.ES), "Tabla"},
        {(ResourceType.Powder, Language.ES), "Polvo"},
        {(ResourceType.PreciousStone, Language.ES), "Piedra preciosa"},
        {(ResourceType.PreservedMeat, Language.ES), "Carne conservada"},
        {(ResourceType.Resource, Language.ES), "Recurso"},
        {(ResourceType.Root, Language.ES), "Raíz"},
        {(ResourceType.Seed, Language.ES), "Semilla"},
        {(ResourceType.Shell, Language.ES), "Cascara"},
        {(ResourceType.Skin, Language.ES), "Piel"},
        {(ResourceType.SmithMagicPotion, Language.ES), "Pócima de forjamagia"},
        {(ResourceType.SmithMagicRune, Language.ES), "Runa de forjamagia"},
        {(ResourceType.Stone, Language.ES), "Piedra bruta"},
        {(ResourceType.StuffedAnimal, Language.ES), "Peluche"},
        {(ResourceType.Tail, Language.ES), "Cola"},
        {(ResourceType.Vegetable, Language.ES), "Legumbre"},
        {(ResourceType.Wing, Language.ES), "Ala"},
        {(ResourceType.Wood, Language.ES), "Madera"},
        {(ResourceType.Wool, Language.ES), "Lana"}
    };
}